CFG_skill = {}
CFG_skill[1] = {id = 1, name = "黄金搭档", skillDesc = "◆黄金搭档：与王景宏齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[2] = {id = 2, name = "得遇明主", skillDesc = "◆得遇明主：与朱棣齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[3] = {id = 3, name = "航海家·战", skillDesc = "◆航海家·战：上阵5位大航海家，自身攻击+800\n", requireCount = 4, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[4] = {id = 4, name = "神兵利器", skillDesc = "◆神兵利器：装备波塞冬之戟，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[5] = {id = 5, name = "航海家·御", skillDesc = "◆航海家·御：上阵5位大航海家，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[6] = {id = 6, name = "万众一心", skillDesc = "◆万众一心：与阿隆索·平松，亚涅斯·平松齐上阵，总伤害+10%\n", requireCount = 2, propertyId = 43, propertyValue = 10, isPassive = 0, power = 360, }
CFG_skill[7] = {id = 7, name = "后继有人", skillDesc = "◆后继有人：与阿隆索·奥赫达齐上阵，自身防御+200\n", requireCount = 1, propertyId = 3, propertyValue = 200, isPassive = 0, power = 60, }
CFG_skill[8] = {id = 8, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[9] = {id = 9, name = "八拜之交", skillDesc = "◆八拜之交：与朱元璋齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[10] = {id = 10, name = "富可敌国", skillDesc = "◆富可敌国：贸易+20%\n", requireCount = 0, propertyId = 8, propertyValue = 20, isPassive = 0, power = 0, }
CFG_skill[11] = {id = 11, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵项链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[12] = {id = 12, name = "大商人", skillDesc = "◆大商人：与马可波罗齐上阵，贸易+20%\n", requireCount = 1, propertyId = 8, propertyValue = 20, isPassive = 0, power = 0, }
CFG_skill[13] = {id = 13, name = "后继有人", skillDesc = "◆后继有人：与胡安·赛拉诺齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[14] = {id = 14, name = "航海家·战", skillDesc = "◆航海家·战：上阵5位大航海家，自身攻击+800\n", requireCount = 4, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[15] = {id = 15, name = "兄弟齐心", skillDesc = "◆兄弟齐心：与胡安·埃尔卡诺，卡尔塔海纳齐上阵，自身攻击+600\n", requireCount = 2, propertyId = 1, propertyValue = 600, isPassive = 0, power = 324, }
CFG_skill[16] = {id = 16, name = "众志成城", skillDesc = "◆众志成城：与凯塞达，若奥·谢兰，路易斯·缅多萨齐上阵，受到伤害减免10%\n", requireCount = 3, propertyId = 42, propertyValue = 10, isPassive = 0, power = 360, }
CFG_skill[17] = {id = 17, name = "领航人", skillDesc = "◆领航人：与伊本·马吉德齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[18] = {id = 18, name = "航海家·御", skillDesc = "◆航海家·御：上阵5位大航海家，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[19] = {id = 19, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之矛，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[20] = {id = 20, name = "兄弟情深", skillDesc = "◆兄弟情深：与保罗·达伽马齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[21] = {id = 21, name = "航海家·御", skillDesc = "◆航海家·御：上阵5位大航海家，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[22] = {id = 22, name = "知人善用", skillDesc = "◆知人善用：与迪尼什齐上阵，自身生命+1200\n", requireCount = 1, propertyId = 5, propertyValue = 1200, isPassive = 0, power = 240, }
CFG_skill[23] = {id = 23, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵圣剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[24] = {id = 24, name = "黑奴贸易", skillDesc = "◆黑奴贸易：与贡萨尔维什齐上阵，贸易+100\n", requireCount = 1, propertyId = 7, propertyValue = 100, isPassive = 0, power = 0, }
CFG_skill[25] = {id = 25, name = "航海家·战", skillDesc = "◆航海家·战：上阵5位大航海家，自身攻击+800\n", requireCount = 4, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[26] = {id = 26, name = "子承父业", skillDesc = "◆子承父业：与迪尼什齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[27] = {id = 27, name = "志同道合", skillDesc = "◆志同道合：与卡布拉尔齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[28] = {id = 28, name = "神兵利器", skillDesc = "◆神兵利器：装备波塞冬之戒，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[29] = {id = 29, name = "志趣相投", skillDesc = "◆志趣相投：与托拜厄斯·弗诺齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[30] = {id = 30, name = "航海家·御", skillDesc = "◆航海家·御：上阵5位大航海家，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[31] = {id = 31, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之铠，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[32] = {id = 32, name = "随船科学家", skillDesc = "◆随船科学家：与约瑟夫·班克斯齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[33] = {id = 33, name = "航海家·战", skillDesc = "◆航海家·战：上阵5位大航海家，自身攻击+800\n", requireCount = 4, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[34] = {id = 34, name = "同仇敌忾", skillDesc = "◆同仇敌忾：与约翰·霍金斯齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[35] = {id = 35, name = "赞助商", skillDesc = "◆赞助商：与伊丽莎白一世齐上阵，贸易+100\n", requireCount = 1, propertyId = 7, propertyValue = 100, isPassive = 0, power = 0, }
CFG_skill[36] = {id = 36, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵指环，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[37] = {id = 37, name = "二十四臣", skillDesc = "◆二十四臣：与郑成功、郑和齐上阵，自身攻击+1000\n", requireCount = 2, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 540, }
CFG_skill[38] = {id = 38, name = "神兵利器", skillDesc = "◆神兵利器：装备波塞冬之链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[39] = {id = 39, name = "大商人", skillDesc = "◆大商人：与沈万三齐上阵，贸易+20%\n", requireCount = 1, propertyId = 8, propertyValue = 20, isPassive = 0, power = 0, }
CFG_skill[40] = {id = 40, name = "东方马可", skillDesc = "◆东方马可：与汪大渊齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[41] = {id = 41, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵之靴，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[42] = {id = 42, name = "德川三杰", skillDesc = "◆德川三杰：与本多忠胜齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[43] = {id = 43, name = "得遇猛士", skillDesc = "◆得遇猛士：与宫本武藏齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[44] = {id = 44, name = "三英杰", skillDesc = "◆三英杰：与丰臣秀吉，织田信长齐上阵，自身生命+2000\n", requireCount = 2, propertyId = 5, propertyValue = 2000, isPassive = 0, power = 150, }
CFG_skill[45] = {id = 45, name = "黄金搭档", skillDesc = "◆黄金搭档：与郑和齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[46] = {id = 46, name = "得遇明主", skillDesc = "◆得遇明主：与朱棣齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[47] = {id = 47, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之盔，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[48] = {id = 48, name = "同名之谊", skillDesc = "◆同名之谊：与约翰·霍金斯齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[49] = {id = 49, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵之盔，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[50] = {id = 50, name = "志同道合", skillDesc = "◆志同道合：与迪亚士齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[51] = {id = 51, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[52] = {id = 52, name = "同名之谊", skillDesc = "◆同名之谊：与约翰·戴维斯齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[53] = {id = 53, name = "同仇敌忾", skillDesc = "◆同仇敌忾：与德雷克齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[54] = {id = 54, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵项链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[55] = {id = 55, name = "平生宿敌", skillDesc = "◆平生宿敌：与佐佐木小次郎齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[56] = {id = 56, name = "寻主求仕", skillDesc = "◆寻主求仕：与德川家康齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[57] = {id = 57, name = "父子情深", skillDesc = "◆父子情深：与朱棣齐上阵，贸易+200\n", requireCount = 1, propertyId = 7, propertyValue = 200, isPassive = 0, power = 0, }
CFG_skill[58] = {id = 58, name = "八拜之交", skillDesc = "◆八拜之交：与沈万三齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[59] = {id = 59, name = "父子情深", skillDesc = "◆父子情深：与朱元璋齐上阵，贸易+200\n", requireCount = 1, propertyId = 7, propertyValue = 200, isPassive = 0, power = 0, }
CFG_skill[60] = {id = 60, name = "知人善用", skillDesc = "◆知人善用：与郑和、王景宏齐上阵，自身攻击+1000\n", requireCount = 2, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 540, }
CFG_skill[61] = {id = 61, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[62] = {id = 62, name = "父子情深", skillDesc = "◆父子情深：与郑芝龙齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[63] = {id = 63, name = "背郑降清", skillDesc = "◆背郑降清：与施琅齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[64] = {id = 64, name = "二十四臣", skillDesc = "◆二十四臣：与戚继光、郑和齐上阵，自身攻击+1000\n", requireCount = 2, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 560, }
CFG_skill[65] = {id = 65, name = "后继有人", skillDesc = "◆后继有人：与迪亚士齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[66] = {id = 66, name = "得遇明主", skillDesc = "◆得遇明主：与亨利王子齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[67] = {id = 67, name = "东方马可", skillDesc = "◆东方马可：与马可波罗齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[68] = {id = 68, name = "后浪前浪", skillDesc = "◆后浪前浪：与郑和齐上阵，贸易+200\n", requireCount = 1, propertyId = 7, propertyValue = 200, isPassive = 0, power = 0, }
CFG_skill[69] = {id = 69, name = "背郑降清", skillDesc = "◆背郑降清：与郑成功、郑芝龙齐上阵，自身攻击+900\n", requireCount = 2, propertyId = 1, propertyValue = 900, isPassive = 0, power = 486, }
CFG_skill[70] = {id = 70, name = "志趣相投", skillDesc = "◆志趣相投：与詹姆斯·库克齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[71] = {id = 71, name = "神兵利器", skillDesc = "◆神兵利器：装备阿瑞斯之矛，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[72] = {id = 72, name = "雇主", skillDesc = "◆雇主：与达伽马齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[73] = {id = 73, name = "平生宿敌", skillDesc = "◆平生宿敌：与宫本武藏齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[74] = {id = 74, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之刃，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[75] = {id = 75, name = "深受感召", skillDesc = "◆深受感召：与德雷克齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[76] = {id = 76, name = "支持文艺", skillDesc = "◆支持文艺：与达·芬奇齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[77] = {id = 77, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之刃，自身攻击+30%\n", requireCount = 1, propertyId = 2, propertyValue = 30, isPassive = 0, power = 360, }
CFG_skill[78] = {id = 78, name = "大帝近臣", skillDesc = "◆大帝近臣：与彼得·罗曼诺夫齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[79] = {id = 79, name = "屡坏好事", skillDesc = "◆屡坏好事：与拿破仑·波拿巴齐上阵，自身防御+400\n", requireCount = 1, propertyId = 3, propertyValue = 400, isPassive = 0, power = 120, }
CFG_skill[80] = {id = 80, name = "神兵利器", skillDesc = "◆神兵利器：装备圣殿骑士剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[81] = {id = 81, name = "前浪后浪", skillDesc = "◆前浪后浪：与彼得·罗曼诺夫齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[82] = {id = 82, name = "神兵利器", skillDesc = "◆神兵利器：装备恺撒大帝剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[83] = {id = 83, name = "屡次遭挫", skillDesc = "◆屡次遭挫：与霍雷肖·纳尔逊齐上阵，自身防御+400\n", requireCount = 1, propertyId = 3, propertyValue = 400, isPassive = 0, power = 120, }
CFG_skill[84] = {id = 84, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[85] = {id = 85, name = "父子情深", skillDesc = "◆父子情深：与约翰·卡博特齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[86] = {id = 86, name = "前浪后浪", skillDesc = "◆前浪后浪：与伊凡雷帝齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[87] = {id = 87, name = "俄史齐名", skillDesc = "◆俄史齐名：与叶卡捷琳娜齐上阵，自身生命+1600\n", requireCount = 1, propertyId = 5, propertyValue = 1600, isPassive = 0, power = 120, }
CFG_skill[88] = {id = 88, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大铠，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[89] = {id = 89, name = "慧眼识人", skillDesc = "◆慧眼识人：与维他斯白令齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[90] = {id = 90, name = "叔侄齐心", skillDesc = "◆叔侄齐心：与约翰·罗斯齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[91] = {id = 91, name = "航海前辈", skillDesc = "◆航海前辈：与威廉·巴芬齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[92] = {id = 92, name = "志同道合", skillDesc = "◆志同道合：与威廉·帕里齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[93] = {id = 93, name = "谁是第一", skillDesc = "◆谁是第一：与哥伦布齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[94] = {id = 94, name = "带头大哥", skillDesc = "◆带头大哥：与麦哲伦齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[95] = {id = 95, name = "志同道合", skillDesc = "◆志同道合：与凯塞达，若奥·谢兰，路易斯·缅多萨，卡尔塔海纳齐上阵，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[96] = {id = 96, name = "继承遗志", skillDesc = "◆继承遗志：与麦哲伦齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[97] = {id = 97, name = "资助文艺", skillDesc = "◆资助文艺：与达·芬奇齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[98] = {id = 98, name = "西史齐名", skillDesc = "◆西史齐名：与科尔特斯齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[99] = {id = 99, name = "得力助手", skillDesc = "◆得力助手：与阿尔马格罗齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[100] = {id = 100, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大戒，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[101] = {id = 101, name = "志同道合", skillDesc = "◆志同道合：与凯塞达，若奥·谢兰，路易斯·缅多萨，胡安·埃尔卡诺齐上阵，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[102] = {id = 102, name = "神兵利器", skillDesc = "◆神兵利器：装备恺撒大帝戒，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[103] = {id = 103, name = "随同伙伴", skillDesc = "◆随同伙伴：与哥伦布齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[104] = {id = 104, name = "西史齐名", skillDesc = "◆西史齐名：与皮萨罗齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[105] = {id = 105, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[106] = {id = 106, name = "结伴同行", skillDesc = "◆结伴同行：与阿隆索·奥赫达齐上阵，自身防御+200\n", requireCount = 1, propertyId = 2, propertyValue = 200, isPassive = 0, power = 60, }
CFG_skill[107] = {id = 107, name = "三英杰", skillDesc = "◆三英杰：与德川家康，织田信长齐上阵，自身生命+3600\n", requireCount = 2, propertyId = 5, propertyValue = 3600, isPassive = 0, power = 270, }
CFG_skill[108] = {id = 108, name = "主仆情深", skillDesc = "◆主仆情深：与九鬼嘉隆，松浦隆信齐上阵，自身攻击+300\n", requireCount = 2, propertyId = 1, propertyValue = 300, isPassive = 0, power = 162, }
CFG_skill[109] = {id = 109, name = "主仆情深", skillDesc = "◆主仆情深：与德川家康齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[110] = {id = 110, name = "神兵利器", skillDesc = "◆神兵利器：装备赵子龙之枪，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[111] = {id = 111, name = "叔侄齐心", skillDesc = "◆叔侄齐心：与克拉克·罗斯齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[112] = {id = 112, name = "领航者", skillDesc = "◆领航者：与伍德斯·罗杰斯齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[113] = {id = 113, name = "继承者", skillDesc = "◆继承者：与詹姆斯·库克齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[114] = {id = 114, name = "俄史齐名", skillDesc = "◆俄史齐名：与彼得·罗曼诺夫齐上阵，自身生命+1600\n", requireCount = 1, propertyId = 5, propertyValue = 1600, isPassive = 0, power = 120, }
CFG_skill[115] = {id = 115, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[116] = {id = 116, name = "继承遗志", skillDesc = "◆继承遗志：与哥伦布齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 120, }
CFG_skill[117] = {id = 117, name = "志同道合", skillDesc = "◆志同道合：与巴尔沃亚齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[118] = {id = 118, name = "志同道合", skillDesc = "◆志同道合：与阿隆索·奥赫达齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[119] = {id = 119, name = "反目成仇", skillDesc = "◆反目成仇：与皮萨罗齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[120] = {id = 120, name = "慧眼识人", skillDesc = "◆慧眼识人：与德雷克齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[121] = {id = 121, name = "主仆情深", skillDesc = "◆主仆情深：与丰臣秀吉齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[122] = {id = 122, name = "神兵利器", skillDesc = "◆神兵利器：装备波斯王子链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[123] = {id = 123, name = "主仆情深", skillDesc = "◆主仆情深：与丰臣秀吉齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[124] = {id = 124, name = "留图指引", skillDesc = "◆留图指引：与克拉克·罗斯，威廉·帕里齐上阵，自身生命+2000\n", requireCount = 2, propertyId = 5, propertyValue = 2000, isPassive = 0, power = 150, }
CFG_skill[125] = {id = 125, name = "得遇明主", skillDesc = "◆得遇明主：与彼得·罗曼诺夫齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[126] = {id = 126, name = "政策支持", skillDesc = "◆政策支持：与波吉亚齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[127] = {id = 127, name = "得到资助", skillDesc = "◆得到资助：与斯福尔扎齐上阵，贸易+150\n", requireCount = 1, propertyId = 7, propertyValue = 150, isPassive = 0, power = 0, }
CFG_skill[128] = {id = 128, name = "志同道合", skillDesc = "◆志同道合：与克拉克·罗斯齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[129] = {id = 129, name = "航海前辈", skillDesc = "◆航海前辈：与威廉·巴芬齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[130] = {id = 130, name = "神兵利器", skillDesc = "◆神兵利器：装备圣殿骑士剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[131] = {id = 131, name = "神兵利器", skillDesc = "◆神兵利器：装备萨拉丁之剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 30, isPassive = 0, power = 360, }
CFG_skill[132] = {id = 132, name = "父子情深", skillDesc = "◆父子情深：与卡伯特齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[133] = {id = 133, name = "神兵利器", skillDesc = "◆神兵利器：装备波斯王子甲，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[134] = {id = 134, name = "父子情深", skillDesc = "◆父子情深：与郑成功齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[135] = {id = 135, name = "神兵利器", skillDesc = "◆神兵利器：装备赵子龙之枪，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[136] = {id = 136, name = "带头大哥", skillDesc = "◆带头大哥：与麦哲伦齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[137] = {id = 137, name = "志同道合", skillDesc = "◆志同道合：与胡安·埃尔卡诺，若奥·谢兰，路易斯·缅多萨，卡尔塔海纳齐上阵，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[138] = {id = 138, name = "志趣相投", skillDesc = "◆志趣相投：与哥伦布齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[139] = {id = 139, name = "兄弟情深", skillDesc = "◆兄弟情深：与亚涅斯·平松齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[140] = {id = 140, name = "三英杰", skillDesc = "◆三英杰：与德川家康，丰臣秀吉齐上阵，自身生命+3600\n", requireCount = 2, propertyId = 5, propertyValue = 3600, isPassive = 0, power = 270, }
CFG_skill[141] = {id = 141, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之刃，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[142] = {id = 142, name = "带头大哥", skillDesc = "◆带头大哥：与麦哲伦齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[143] = {id = 143, name = "志同道合", skillDesc = "◆志同道合：与胡安·埃尔卡诺，凯塞达，路易斯·缅多萨，卡尔塔海纳齐上阵，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[144] = {id = 144, name = "带头大哥", skillDesc = "◆带头大哥：与麦哲伦齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[145] = {id = 145, name = "志同道合", skillDesc = "◆志同道合：与胡安·埃尔卡诺，凯塞达，若奥·谢兰，卡尔塔海纳齐上阵，自身防御+800\n", requireCount = 4, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[146] = {id = 146, name = "志趣相投", skillDesc = "◆志趣相投：与哥伦布齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[147] = {id = 147, name = "兄弟情深", skillDesc = "◆兄弟情深：与阿隆索·平松齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[148] = {id = 148, name = "随其航海", skillDesc = "◆随其航海：与詹姆斯·库克齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[149] = {id = 149, name = "黑奴贸易", skillDesc = "◆黑奴贸易：与亨利王子齐上阵，贸易+200\n", requireCount = 1, propertyId = 7, propertyValue = 200, isPassive = 0, power = 0, }
CFG_skill[150] = {id = 150, name = "神兵利器", skillDesc = "◆神兵利器：装备圣殿骑士剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[151] = {id = 151, name = "神兵利器", skillDesc = "◆神兵利器：与拉奥孔战刀齐上阵，自身攻击+30%\n", requireCount = 1, propertyId = 2, propertyValue = 30, isPassive = 0, power = 360, }
CFG_skill[152] = {id = 152, name = "随其航海", skillDesc = "◆随其航海：与詹姆斯·库克齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[153] = {id = 153, name = "神兵利器", skillDesc = "◆神兵利器：装备圣殿骑士戒，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[154] = {id = 154, name = "被领航人", skillDesc = "◆被领航人：与威廉·丹皮尔齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[155] = {id = 155, name = "兄弟情深", skillDesc = "◆兄弟情深：与达伽马齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[156] = {id = 156, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之戒，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[157] = {id = 157, name = "最佳搭档", skillDesc = "◆最佳搭档：与阿迪肯齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[158] = {id = 158, name = "忠实伙伴", skillDesc = "◆忠实伙伴：与阿尔米达齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[159] = {id = 159, name = "神兵利器", skillDesc = "◆神兵利器：装备圣殿骑士铠，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[160] = {id = 160, name = "最佳搭档", skillDesc = "◆最佳搭档：与赫德拉姆齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[161] = {id = 161, name = "忠实伙伴", skillDesc = "◆忠实伙伴：与赫德拉姆齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[162] = {id = 162, name = "青梅竹马", skillDesc = "◆青梅竹马：与卡米尔齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[163] = {id = 163, name = "识人善用", skillDesc = "◆识人善用：与费南德·迪阿斯齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[164] = {id = 164, name = "平生宿敌", skillDesc = "◆平生宿敌：与克利福德齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[165] = {id = 165, name = "青梅竹马", skillDesc = "◆青梅竹马：与丽璐·阿歌特齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[166] = {id = 166, name = "志趣相投", skillDesc = "◆志趣相投：与丽璐·阿歌特齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[167] = {id = 167, name = "父爱如山", skillDesc = "◆父爱如山：与杨希恩齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[168] = {id = 168, name = "平生宿敌", skillDesc = "◆平生宿敌：与克利福德齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[169] = {id = 169, name = "神兵利器", skillDesc = "◆神兵利器：装备萨拉丁之剑，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[170] = {id = 170, name = "视如己出", skillDesc = "◆视如己出：与玛莉亚·李齐上阵，自身防御+200\n", requireCount = 1, propertyId = 3, propertyValue = 200, isPassive = 0, power = 60, }
CFG_skill[171] = {id = 171, name = "神兵利器", skillDesc = "◆神兵利器：装备赵子龙之枪，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[172] = {id = 172, name = "平生宿敌", skillDesc = "◆平生宿敌：与玛莉亚·李，丽璐·阿歌特齐上阵，自身攻击+300\n", requireCount = 2, propertyId = 1, propertyValue = 300, isPassive = 0, power = 162, }
CFG_skill[173] = {id = 173, name = "亦敌亦友", skillDesc = "◆亦敌亦友：与蒂雅·恰斯卡齐上阵，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[174] = {id = 174, name = "一生挚友", skillDesc = "◆一生挚友：与林·森齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[175] = {id = 175, name = "相敬如宾", skillDesc = "◆相敬如宾：与塞西莉雅齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[176] = {id = 176, name = "一生挚友", skillDesc = "◆一生挚友：与杏太郞·佐伯齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[177] = {id = 177, name = "相敬如宾", skillDesc = "◆相敬如宾：与杏太郞·佐伯齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[178] = {id = 178, name = "母慈子孝", skillDesc = "◆母慈子孝：与爱斯法妮雅齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[179] = {id = 179, name = "同命相怜", skillDesc = "◆同命相怜：与蒂雅·恰斯卡齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[180] = {id = 180, name = "近身保镖", skillDesc = "◆近身保镖：与德尼雅齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[181] = {id = 181, name = "主仆情深", skillDesc = "◆主仆情深：与阿米娜齐上阵，自身生命+400\n", requireCount = 1, propertyId = 5, propertyValue = 400, isPassive = 0, power = 30, }
CFG_skill[182] = {id = 182, name = "贴身保护", skillDesc = "◆贴身保护：与易文·伍丁齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[183] = {id = 183, name = "主仆情深", skillDesc = "◆主仆情深：与易文·伍丁齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[184] = {id = 184, name = "温暖内心", skillDesc = "◆温暖内心：与爱斯法妮雅齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[185] = {id = 185, name = "同命相怜", skillDesc = "◆同命相怜：与易文·伍丁齐上阵，自身生命+800\n", requireCount = 1, propertyId = 5, propertyValue = 800, isPassive = 0, power = 60, }
CFG_skill[186] = {id = 186, name = "亦敌亦友", skillDesc = "◆亦敌亦友：与杏太郞·佐伯齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[187] = {id = 187, name = "救命之恩", skillDesc = "◆救命之恩：与柳科·西萨齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[188] = {id = 188, name = "救命之恩", skillDesc = "◆救命之恩：与蒂雅·恰斯卡齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[189] = {id = 189, name = "母慈子孝", skillDesc = "◆母慈子孝：与塞西莉雅齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[190] = {id = 190, name = "善解人意", skillDesc = "◆善解人意：与阿米娜齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[191] = {id = 191, name = "兄妹情深", skillDesc = "◆兄妹情深：与乙凤·宋齐上阵，自身攻击+100 \n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[192] = {id = 192, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之刃，自身攻击+20%\n", requireCount = 1, propertyId = 2, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[193] = {id = 193, name = "兄妹情深", skillDesc = "◆兄妹情深：与桑亨·韩齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[194] = {id = 194, name = "心腹爱将", skillDesc = "◆心腹爱将：与西门·李纳列斯齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[195] = {id = 195, name = "心腹爱将", skillDesc = "◆心腹爱将：与巴鲁迪斯齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[196] = {id = 196, name = "勾心斗角", skillDesc = "◆勾心斗角：与埃斯康特齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[197] = {id = 197, name = "心腹爱将", skillDesc = "◆心腹爱将：与埃斯康特齐上阵，自身防御+100\n", requireCount = 1, propertyId = 3, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[198] = {id = 198, name = "慧眼识人", skillDesc = "◆慧眼识人：与蒂雅·恰斯卡齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[199] = {id = 199, name = "勾心斗角", skillDesc = "◆勾心斗角：与玛尔德纳德齐上阵，自身攻击+100\n", requireCount = 1, propertyId = 1, propertyValue = 100, isPassive = 0, power = 54, }
CFG_skill[200] = {id = 200, name = "心腹爱将", skillDesc = "◆心腹爱将：与芬·布兰科齐上阵，自身防御+100\n", requireCount = 1, propertyId = 4, propertyValue = 100, isPassive = 0, power = 30, }
CFG_skill[201] = {id = 201, name = "天赋神通", skillDesc = "◆天赋神通：总减伤+6%\n", requireCount = 0, propertyId = 42, propertyValue = 6, isPassive = 0, power = 120, }
CFG_skill[202] = {id = 202, name = "天赋神通", skillDesc = "◆天赋神通：总伤害+5%\n", requireCount = 0, propertyId = 43, propertyValue = 5, isPassive = 0, power = 120, }
CFG_skill[203] = {id = 203, name = "天赋神通", skillDesc = "◆天赋神通：总生命+8%\n", requireCount = 0, propertyId = 64, propertyValue = 8, isPassive = 0, power = 120, }
CFG_skill[204] = {id = 204, name = "天赋神通", skillDesc = "◆天赋神通：总暴击+10%\n", requireCount = 0, propertyId = 14, propertyValue = 10, isPassive = 0, power = 120, }
CFG_skill[205] = {id = 205, name = "天赋神通", skillDesc = "◆天赋神通：总闪避+10%\n", requireCount = 0, propertyId = 12, propertyValue = 10, isPassive = 0, power = 120, }
CFG_skill[206] = {id = 206, name = "勇猛", skillDesc = "◆勇猛：不上阵时，给船队附加自身4%的攻击\n", requireCount = 0, propertyId = 2, propertyValue = 4, isPassive = 1, power = 10, }
CFG_skill[207] = {id = 207, name = "刚毅", skillDesc = "◆刚毅：不上阵时，给船队附加自身4%的防御\n", requireCount = 0, propertyId = 4, propertyValue = 4, isPassive = 1, power = 10, }
CFG_skill[208] = {id = 208, name = "厚德", skillDesc = "◆厚德：不上阵时，给船队附加自身4%的生命\n", requireCount = 0, propertyId = 6, propertyValue = 4, isPassive = 1, power = 10, }
CFG_skill[209] = {id = 209, name = "睿智", skillDesc = "◆睿智：不上阵时，给船队附加自身4%的贸易\n", requireCount = 0, propertyId = 8, propertyValue = 4, isPassive = 1, power = 0, }
CFG_skill[210] = {id = 210, name = "天赋神通", skillDesc = "◆天赋神通：总减伤+7%\n", requireCount = 0, propertyId = 42, propertyValue = 7, isPassive = 0, power = 144, }
CFG_skill[211] = {id = 211, name = "天赋神通", skillDesc = "◆天赋神通：总伤害+6%\n", requireCount = 0, propertyId = 43, propertyValue = 6, isPassive = 0, power = 144, }
CFG_skill[212] = {id = 212, name = "天赋神通", skillDesc = "◆天赋神通：总生命+9%\n", requireCount = 0, propertyId = 64, propertyValue = 9, isPassive = 0, power = 144, }
CFG_skill[213] = {id = 213, name = "天赋神通", skillDesc = "◆天赋神通：总暴击+12%\n", requireCount = 0, propertyId = 14, propertyValue = 12, isPassive = 0, power = 144, }
CFG_skill[214] = {id = 214, name = "天赋神通", skillDesc = "◆天赋神通：总闪避+12%\n", requireCount = 0, propertyId = 12, propertyValue = 12, isPassive = 0, power = 144, }
CFG_skill[215] = {id = 215, name = "天赋神通", skillDesc = "◆天赋神通：总减伤+8%\n", requireCount = 0, propertyId = 42, propertyValue = 8, isPassive = 0, power = 168, }
CFG_skill[216] = {id = 216, name = "天赋神通", skillDesc = "◆天赋神通：总伤害+7%\n", requireCount = 0, propertyId = 43, propertyValue = 7, isPassive = 0, power = 168, }
CFG_skill[217] = {id = 217, name = "天赋神通", skillDesc = "◆天赋神通：总生命+10%\n", requireCount = 0, propertyId = 64, propertyValue = 10, isPassive = 0, power = 168, }
CFG_skill[218] = {id = 218, name = "天赋神通", skillDesc = "◆天赋神通：总暴击+14%\n", requireCount = 0, propertyId = 14, propertyValue = 14, isPassive = 0, power = 168, }
CFG_skill[219] = {id = 219, name = "天赋神通", skillDesc = "◆天赋神通：总闪避+14%\n", requireCount = 0, propertyId = 12, propertyValue = 14, isPassive = 0, power = 168, }
CFG_skill[220] = {id = 220, name = "天赋神通", skillDesc = "◆天赋神通：总减伤+9%\n", requireCount = 0, propertyId = 42, propertyValue = 9, isPassive = 0, power = 192, }
CFG_skill[221] = {id = 221, name = "天赋神通", skillDesc = "◆天赋神通：总伤害+8%\n", requireCount = 0, propertyId = 43, propertyValue = 8, isPassive = 0, power = 192, }
CFG_skill[222] = {id = 222, name = "天赋神通", skillDesc = "◆天赋神通：总生命+12%\n", requireCount = 0, propertyId = 64, propertyValue = 12, isPassive = 0, power = 192, }
CFG_skill[223] = {id = 223, name = "天赋神通", skillDesc = "◆天赋神通：总暴击+16%\n", requireCount = 0, propertyId = 14, propertyValue = 16, isPassive = 0, power = 192, }
CFG_skill[224] = {id = 224, name = "天赋神通", skillDesc = "◆天赋神通：总闪避+16%\n", requireCount = 0, propertyId = 12, propertyValue = 16, isPassive = 0, power = 192, }
CFG_skill[225] = {id = 225, name = "专属武器", skillDesc = "◆专属武器：装备征服者权杖，贸易+20%\n", requireCount = 1, propertyId = 8, propertyValue = 20, isPassive = 0, power = 0, }
CFG_skill[226] = {id = 226, name = "黄金海盗", skillDesc = "◆黄金海盗：与爱德华，埃里克齐上阵，自身攻击+1000\n", requireCount = 2, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 540, }
CFG_skill[227] = {id = 227, name = "黄金海盗", skillDesc = "◆黄金海盗：与埃夫里，埃里克齐上阵，自身攻击+900\n", requireCount = 2, propertyId = 1, propertyValue = 900, isPassive = 0, power = 486, }
CFG_skill[228] = {id = 228, name = "黄金海盗", skillDesc = "◆黄金海盗：与爱德华，埃夫里齐上阵，自身攻击+900\n", requireCount = 2, propertyId = 1, propertyValue = 900, isPassive = 0, power = 486, }
CFG_skill[229] = {id = 229, name = "遭遇大敌", skillDesc = "◆遭遇大敌：与九鬼嘉隆齐上阵，自身攻击+200\n", requireCount = 1, propertyId = 1, propertyValue = 200, isPassive = 0, power = 108, }
CFG_skill[230] = {id = 230, name = "终成威名", skillDesc = "◆终成威名：与村上武吉齐上阵，自身攻击+400\n", requireCount = 1, propertyId = 1, propertyValue = 400, isPassive = 0, power = 216, }
CFG_skill[231] = {id = 231, name = "择木而栖", skillDesc = "◆择木而栖：与丰臣秀吉齐上阵，自身防御+400\n", requireCount = 1, propertyId = 3, propertyValue = 400, isPassive = 0, power = 120, }
CFG_skill[232] = {id = 232, name = "随船航海", skillDesc = "◆随船航海：与詹姆斯·库克齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[233] = {id = 233, name = "海盗兄弟", skillDesc = "◆海盗兄弟：与杰克·斯帕罗齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[234] = {id = 234, name = "海盗兄弟", skillDesc = "◆海盗兄弟：与巴沙洛缪齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[235] = {id = 235, name = "高额悬赏", skillDesc = "◆高额悬赏：与朱元璋，朱棣齐上阵，自身攻击+1000\n", requireCount = 2, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 540, }
CFG_skill[236] = {id = 236, name = "高额悬赏", skillDesc = "◆高额悬赏：与陈祖义齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[237] = {id = 237, name = "遭遇克星", skillDesc = "◆遭遇克星：与郑和齐上阵，自身防御+800\n", requireCount = 1, propertyId = 3, propertyValue = 800, isPassive = 0, power = 240, }
CFG_skill[238] = {id = 238, name = "海灵套装", skillDesc = "◆海灵套装：装备一套海灵套装，自身攻击+50%\n", requireCount = 6, propertyId = 2, propertyValue = 50, isPassive = 0, power = 600, }
CFG_skill[239] = {id = 239, name = "战神套装", skillDesc = "◆战神套装：装备一套战神套装，自身攻击+60%\n", requireCount = 6, propertyId = 2, propertyValue = 60, isPassive = 0, power = 720, }
CFG_skill[240] = {id = 240, name = "海神套装", skillDesc = "◆海神套装：装备一套海神套装，自身攻击+70%\n", requireCount = 6, propertyId = 2, propertyValue = 70, isPassive = 0, power = 840, }
CFG_skill[241] = {id = 241, name = "最佳拍档", skillDesc = "◆最佳拍档：与安妮齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[242] = {id = 242, name = "最佳拍档", skillDesc = "◆最佳拍档：与玛莉齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[243] = {id = 243, name = "老情人", skillDesc = "◆老情人：与杰克·斯帕罗齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[244] = {id = 244, name = "老情人", skillDesc = "◆老情人：与安吉莉卡齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[245] = {id = 245, name = "舍己救父", skillDesc = "◆舍己救父：与爱德华·蒂奇齐上阵，自身攻击+800\n", requireCount = 1, propertyId = 1, propertyValue = 800, isPassive = 0, power = 432, }
CFG_skill[246] = {id = 246, name = "海盗父女", skillDesc = "◆海盗父女：与安吉莉卡齐上阵，自身生命+3200\n", requireCount = 1, propertyId = 5, propertyValue = 3200, isPassive = 0, power = 240, }
CFG_skill[247] = {id = 247, name = "神兵利器", skillDesc = "◆神兵利器：装备海灵宝甲，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[248] = {id = 248, name = "神兵利器", skillDesc = "◆神兵利器：装备赵子龙之盔，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[249] = {id = 249, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之冠，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[250] = {id = 250, name = "神兵利器", skillDesc = "◆神兵利器：装备七海之甲，自身防御+20%\n", requireCount = 1, propertyId = 4, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[251] = {id = 251, name = "神兵利器", skillDesc = "◆神兵利器：装备波斯王子链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[252] = {id = 252, name = "神兵利器", skillDesc = "◆神兵利器：装备赵子龙之链，自身生命+20%\n", requireCount = 1, propertyId = 6, propertyValue = 20, isPassive = 0, power = 240, }
CFG_skill[253] = {id = 253, name = "海贼·战", skillDesc = "◆海贼·战：上阵5位海贼王，自身攻击+1000\n", requireCount = 5, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 432, }
CFG_skill[254] = {id = 254, name = "海贼王·战", skillDesc = "◆海贼王·战：上阵10位海贼王，自身攻击+30%\n", requireCount = 10, propertyId = 2, propertyValue = 30, isPassive = 0, power = 300, }
CFG_skill[255] = {id = 255, name = "海贼·御", skillDesc = "◆海贼·御：上阵5位海贼王，自身防御+1000\n", requireCount = 5, propertyId = 3, propertyValue = 1000, isPassive = 0, power = 240, }
CFG_skill[256] = {id = 256, name = "海贼王·御", skillDesc = "◆海贼王·御：上阵10位海贼王，自身防御+30%\n", requireCount = 10, propertyId = 4, propertyValue = 30, isPassive = 0, power = 300, }
CFG_skill[261] = {id = 261, name = "绿色升星1", skillDesc = "★升星Ⅰ：贸易+10%%(%d星激活)\n", requireCount = 0, propertyId = 8, propertyValue = 10, isPassive = 0, power = 0, }
CFG_skill[262] = {id = 262, name = "绿色升星2", skillDesc = "★升星Ⅱ：自身攻击+500(%d星激活)\n", requireCount = 0, propertyId = 1, propertyValue = 500, isPassive = 0, power = 200, }
CFG_skill[263] = {id = 263, name = "绿色升星3", skillDesc = "★升星Ⅲ：自身防御+200(%d星激活)\n", requireCount = 0, propertyId = 3, propertyValue = 1500, isPassive = 0, power = 250, }
CFG_skill[264] = {id = 264, name = "绿色升星4", skillDesc = "★升星Ⅳ：自身生命+800(%d星激活)\n", requireCount = 0, propertyId = 5, propertyValue = 800, isPassive = 0, power = 300, }
CFG_skill[265] = {id = 265, name = "绿色升星5", skillDesc = "★升星Ⅴ：总闪避+10%%(%d星激活)\n", requireCount = 0, propertyId = 12, propertyValue = 10, isPassive = 0, power = 400, }
CFG_skill[266] = {id = 266, name = "绿色升星6", skillDesc = "★升星Ⅵ：总命中+10%%(%d星激活)\n", requireCount = 0, propertyId = 10, propertyValue = 10, isPassive = 0, power = 500, }
CFG_skill[267] = {id = 267, name = "绿色升星7", skillDesc = "★升星Ⅶ：总暴击+10%%(%d星激活)\n", requireCount = 0, propertyId = 14, propertyValue = 10, isPassive = 0, power = 600, }
CFG_skill[268] = {id = 268, name = "绿色升星8", skillDesc = "★升星Ⅷ：自身防御+5%%(%d星激活)\n", requireCount = 0, propertyId = 4, propertyValue = 5, isPassive = 0, power = 700, }
CFG_skill[269] = {id = 269, name = "绿色升星9", skillDesc = "★升星Ⅸ：自身攻击+8%%(%d星激活)\n", requireCount = 0, propertyId = 2, propertyValue = 8, isPassive = 0, power = 850, }
CFG_skill[270] = {id = 270, name = "绿色升星10", skillDesc = "★升星Ⅹ：自身生命+10%%(%d星激活)\n", requireCount = 0, propertyId = 6, propertyValue = 10, isPassive = 0, power = 1000, }
CFG_skill[271] = {id = 271, name = "蓝色升星1", skillDesc = "★升星Ⅰ：贸易+15%%(%d星激活)\n", requireCount = 0, propertyId = 8, propertyValue = 15, isPassive = 0, power = 300, }
CFG_skill[272] = {id = 272, name = "蓝色升星2", skillDesc = "★升星Ⅱ：自身攻击+750(%d星激活)\n", requireCount = 0, propertyId = 1, propertyValue = 750, isPassive = 0, power = 350, }
CFG_skill[273] = {id = 273, name = "蓝色升星3", skillDesc = "★升星Ⅲ：自身防御+250(%d星激活)\n", requireCount = 0, propertyId = 3, propertyValue = 250, isPassive = 0, power = 400, }
CFG_skill[274] = {id = 274, name = "蓝色升星4", skillDesc = "★升星Ⅳ：自身生命+1000(%d星激活)\n", requireCount = 0, propertyId = 5, propertyValue = 1000, isPassive = 0, power = 500, }
CFG_skill[275] = {id = 275, name = "蓝色升星5", skillDesc = "★升星Ⅴ：总闪避+15%%(%d星激活)\n", requireCount = 0, propertyId = 12, propertyValue = 15, isPassive = 0, power = 600, }
CFG_skill[276] = {id = 276, name = "蓝色升星6", skillDesc = "★升星Ⅵ：总命中+15%%(%d星激活)\n", requireCount = 0, propertyId = 10, propertyValue = 15, isPassive = 0, power = 700, }
CFG_skill[277] = {id = 277, name = "蓝色升星7", skillDesc = "★升星Ⅶ：总暴击+15%%(%d星激活)\n", requireCount = 0, propertyId = 14, propertyValue = 15, isPassive = 0, power = 850, }
CFG_skill[278] = {id = 278, name = "蓝色升星8", skillDesc = "★升星Ⅷ：自身防御+8%%(%d星激活)\n", requireCount = 0, propertyId = 4, propertyValue = 8, isPassive = 0, power = 1000, }
CFG_skill[279] = {id = 279, name = "蓝色升星9", skillDesc = "★升星Ⅸ：自身攻击+11%%(%d星激活)\n", requireCount = 0, propertyId = 2, propertyValue = 11, isPassive = 0, power = 1200, }
CFG_skill[280] = {id = 280, name = "蓝色升星10", skillDesc = "★升星Ⅹ：自身生命+15%%(%d星激活)\n", requireCount = 0, propertyId = 6, propertyValue = 15, isPassive = 0, power = 1400, }
CFG_skill[281] = {id = 281, name = "紫色升星1", skillDesc = "★升星Ⅰ：贸易+20%%(%d星激活)\n", requireCount = 0, propertyId = 8, propertyValue = 20, isPassive = 0, power = 500, }
CFG_skill[282] = {id = 282, name = "紫色升星2", skillDesc = "★升星Ⅱ：自身攻击+1000(%d星激活)\n", requireCount = 0, propertyId = 1, propertyValue = 1000, isPassive = 0, power = 600, }
CFG_skill[283] = {id = 283, name = "紫色升星3", skillDesc = "★升星Ⅲ：自身防御+300(%d星激活)\n", requireCount = 0, propertyId = 3, propertyValue = 300, isPassive = 0, power = 700, }
CFG_skill[284] = {id = 284, name = "紫色升星4", skillDesc = "★升星Ⅳ：自身生命+1200(%d星激活)\n", requireCount = 0, propertyId = 5, propertyValue = 1200, isPassive = 0, power = 800, }
CFG_skill[285] = {id = 285, name = "紫色升星5", skillDesc = "★升星Ⅴ：总闪避+20%%(%d星激活)\n", requireCount = 0, propertyId = 12, propertyValue = 20, isPassive = 0, power = 900, }
CFG_skill[286] = {id = 286, name = "紫色升星6", skillDesc = "★升星Ⅵ：总命中+20%%(%d星激活)\n", requireCount = 0, propertyId = 10, propertyValue = 20, isPassive = 0, power = 1000, }
CFG_skill[287] = {id = 287, name = "紫色升星7", skillDesc = "★升星Ⅶ：总暴击+20%%(%d星激活)\n", requireCount = 0, propertyId = 14, propertyValue = 20, isPassive = 0, power = 1200, }
CFG_skill[288] = {id = 288, name = "紫色升星8", skillDesc = "★升星Ⅷ：自身防御+11%%(%d星激活)\n", requireCount = 0, propertyId = 4, propertyValue = 11, isPassive = 0, power = 1400, }
CFG_skill[289] = {id = 289, name = "紫色升星9", skillDesc = "★升星Ⅸ：自身攻击+15%%(%d星激活)\n", requireCount = 0, propertyId = 2, propertyValue = 15, isPassive = 0, power = 1600, }
CFG_skill[290] = {id = 290, name = "紫色升星10", skillDesc = "★升星Ⅹ：自身生命+20%%(%d星激活)\n", requireCount = 0, propertyId = 6, propertyValue = 20, isPassive = 0, power = 1800, }
CFG_skill[291] = {id = 291, name = "橙色升星1", skillDesc = "★升星Ⅰ：贸易+25%%(%d星激活)\n", requireCount = 0, propertyId = 8, propertyValue = 25, isPassive = 0, power = 600, }
CFG_skill[292] = {id = 292, name = "橙色升星2", skillDesc = "★升星Ⅱ：自身攻击+1250(%d星激活)\n", requireCount = 0, propertyId = 1, propertyValue = 1250, isPassive = 0, power = 700, }
CFG_skill[293] = {id = 293, name = "橙色升星3", skillDesc = "★升星Ⅲ：自身防御+350(%d星激活)\n", requireCount = 0, propertyId = 3, propertyValue = 350, isPassive = 0, power = 800, }
CFG_skill[294] = {id = 294, name = "橙色升星4", skillDesc = "★升星Ⅳ：自身生命+1400(%d星激活)\n", requireCount = 0, propertyId = 5, propertyValue = 1400, isPassive = 0, power = 900, }
CFG_skill[295] = {id = 295, name = "橙色升星5", skillDesc = "★升星Ⅴ：总闪避+25%%(%d星激活)\n", requireCount = 0, propertyId = 12, propertyValue = 25, isPassive = 0, power = 1000, }
CFG_skill[296] = {id = 296, name = "橙色升星6", skillDesc = "★升星Ⅵ：总命中+25%%(%d星激活)\n", requireCount = 0, propertyId = 10, propertyValue = 25, isPassive = 0, power = 1200, }
CFG_skill[297] = {id = 297, name = "橙色升星7", skillDesc = "★升星Ⅶ：总暴击+25%%(%d星激活)\n", requireCount = 0, propertyId = 14, propertyValue = 25, isPassive = 0, power = 1400, }
CFG_skill[298] = {id = 298, name = "橙色升星8", skillDesc = "★升星Ⅷ：自身防御+15%%(%d星激活)\n", requireCount = 0, propertyId = 4, propertyValue = 15, isPassive = 0, power = 1600, }
CFG_skill[299] = {id = 299, name = "橙色升星9", skillDesc = "★升星Ⅸ：自身攻击+20%%(%d星激活)\n", requireCount = 0, propertyId = 2, propertyValue = 20, isPassive = 0, power = 1800, }
CFG_skill[300] = {id = 300, name = "橙色升星10", skillDesc = "★升星Ⅹ：自身生命+25%%(%d星激活)\n", requireCount = 0, propertyId = 6, propertyValue = 25, isPassive = 0, power = 2000, }
CFG_skill[400] = {id = 400, name = "同族之谜", skillDesc = "◆同族之谜：与郑石氏齐上阵，自身生命+1000\n", requireCount = 1, propertyId = 5, propertyValue = 1500, isPassive = 0, power = 75, }
CFG_skill[401] = {id = 401, name = "同族之谜", skillDesc = "◆同族之谜：与郑和齐上阵，自身生命+1000\n", requireCount = 1, propertyId = 5, propertyValue = 1500, isPassive = 0, power = 75, }
CFG_skill[402] = {id = 402, name = "探索者", skillDesc = "◆探索者：与麦哲伦齐上阵，自身贸易+100\n", requireCount = 1, propertyId = 7, propertyValue = 100, isPassive = 0, power = 0, }
CFG_skill[403] = {id = 403, name = "探索者", skillDesc = "◆探索者：与哥伦布齐上阵，自身贸易+100\n", requireCount = 1, propertyId = 7, propertyValue = 100, isPassive = 0, power = 0, }
CFG_skill[404] = {id = 404, name = "神兵利器", skillDesc = "◆神兵利器：装备亚历山大之戒，自身贸易+20%\n", requireCount = 1, propertyId = 8, propertyValue = 20, isPassive = 0, power = 0, }
CFG_skill[405] = {id = 405, name = "海峡命名者", skillDesc = "◆海峡命名者：与德雷克齐上阵，自身防御+600\n", requireCount = 1, propertyId = 3, propertyValue = 600, isPassive = 0, power = 180, }
CFG_skill[406] = {id = 406, name = "海峡命名者", skillDesc = "◆海峡命名者：与麦哲伦齐上阵，自身防御+600\n", requireCount = 1, propertyId = 3, propertyValue = 600, isPassive = 0, power = 180, }
CFG_skill[407] = {id = 407, name = "东方海贼", skillDesc = "◆东方海贼：与郑石氏齐上阵，自身攻击+600\n", requireCount = 1, propertyId = 1, propertyValue = 600, isPassive = 0, power = 180, }