CFG_skillEffect = {}
CFG_skillEffect[1] = {id = 1, target = 1, time = -1, resId = "1", scale = 0, autoDestroy = 0, }
CFG_skillEffect[2] = {id = 2, target = 1, time = -1, resId = "2", scale = 10, autoDestroy = 0, }
CFG_skillEffect[3] = {id = 3, target = 1, time = -1, resId = "3", scale = 10, autoDestroy = 0, }
CFG_skillEffect[4] = {id = 4, target = 1, time = -1, resId = "4", scale = 10, autoDestroy = 0, }
CFG_skillEffect[5] = {id = 5, target = 1, time = -1, resId = "5", scale = 10, autoDestroy = 0, }
CFG_skillEffect[6] = {id = 6, target = 1, time = -1, resId = "6", scale = 10, autoDestroy = 0, }
CFG_skillEffect[7] = {id = 7, target = 0, time = 2, resId = "7", scale = 0, autoDestroy = 1, }
CFG_skillEffect[8] = {id = 8, target = 1, time = -1, resId = "8", scale = 0, autoDestroy = 0, }
CFG_skillEffect[9] = {id = 9, target = 1, time = -1, resId = "9", scale = 0, autoDestroy = 0, }
CFG_skillEffect[10] = {id = 10, target = 0, time = 2, resId = "10", scale = 0, autoDestroy = 1, }
CFG_skillEffect[11] = {id = 11, target = 1, time = -1, resId = "11", scale = 0, autoDestroy = 0, }
CFG_skillEffect[12] = {id = 12, target = 1, time = -1, resId = "12", scale = 0, autoDestroy = 0, }
CFG_skillEffect[13] = {id = 13, target = 1, time = -1, resId = "13", scale = 6, autoDestroy = 0, }
CFG_skillEffect[14] = {id = 14, target = 1, time = -1, resId = "14", scale = 7, autoDestroy = 0, }
CFG_skillEffect[15] = {id = 15, target = 1, time = -1, resId = "15", scale = 5, autoDestroy = 0, }
CFG_skillEffect[16] = {id = 16, target = 1, time = -1, resId = "16", scale = 1.5, autoDestroy = 0, }
CFG_skillEffect[17] = {id = 17, target = 1, time = -1, resId = "17", scale = 6, autoDestroy = 0, }
CFG_skillEffect[18] = {id = 18, target = 1, time = -1, resId = "18", scale = 0, autoDestroy = 0, }
CFG_skillEffect[19] = {id = 19, target = 1, time = 3, resId = "19", scale = 0, autoDestroy = 0, }
CFG_skillEffect[20] = {id = 20, target = 1, time = -1, resId = "20", scale = 1.7, autoDestroy = 0, }
CFG_skillEffect[21] = {id = 21, target = 1, time = -1, resId = "24", scale = 0, autoDestroy = 0, }
CFG_skillEffect[22] = {id = 22, target = 1, time = -1, resId = "22", scale = 0, autoDestroy = 0, }
CFG_skillEffect[23] = {id = 23, target = 1, time = -1, resId = "23", scale = 0, autoDestroy = 0, }
CFG_skillEffect[24] = {id = 24, target = 1, time = -1, resId = "24", scale = 0, autoDestroy = 0, }
CFG_skillEffect[25] = {id = 25, target = 1, time = 2, resId = "25", scale = 0, autoDestroy = 1, }
CFG_skillEffect[27] = {id = 27, target = 0, time = 2, resId = "27", scale = 0, autoDestroy = 1, }
CFG_skillEffect[31] = {id = 31, target = 0, time = 2, resId = "31", scale = 0, autoDestroy = 1, }
CFG_skillEffect[32] = {id = 32, target = 0, time = 3, resId = "32", scale = 0, autoDestroy = 1, }
CFG_skillEffect[33] = {id = 33, target = 0, time = 0.3, resId = "33", scale = 0, autoDestroy = 1, }
CFG_skillEffect[34] = {id = 34, target = 0, time = 6, resId = "34", scale = 0, autoDestroy = 1, }
CFG_skillEffect[35] = {id = 35, target = 0, time = 6, resId = "35", scale = 0, autoDestroy = 1, }
CFG_skillEffect[36] = {id = 36, target = 0, time = 1, resId = "36", scale = 0, autoDestroy = 1, }
CFG_skillEffect[37] = {id = 37, target = 0, time = 0.3, resId = "37", scale = 0, autoDestroy = 1, }
CFG_skillEffect[38] = {id = 38, target = 0, time = 1, resId = "38", scale = 0, autoDestroy = 1, }
CFG_skillEffect[39] = {id = 39, target = 0, time = 5, resId = "39", scale = 0, autoDestroy = 1, }
CFG_skillEffect[40] = {id = 40, target = 1, time = 13, resId = "40", scale = 0, autoDestroy = 1, }
CFG_skillEffect[41] = {id = 41, target = 1, time = 13, resId = "41", scale = 0, autoDestroy = 1, }
CFG_skillEffect[42] = {id = 42, target = 0, time = 5, resId = "42", scale = 0, autoDestroy = 1, }
CFG_skillEffect[43] = {id = 43, target = 1, time = 5, resId = "43", scale = 0, autoDestroy = 1, }