
PackatHead = {
	ACCOUNT = 0,
	CHAT = 1,
	PLAYER = 2,
	SAILOR = 3,
	HARBOR = 4,
	GOODS = 5,
	SHIP = 6,
	LAB = 7,
	SKILL = 8,
	EQUIP = 9,
	ENEMY=10,
	BATTLE=11,
	ITEM=12,
	RELATION=13,
	INSERVER=14,
	FAMILY=15,
	COPYMAP=16,
	QUEST=17,
	MERCHANT=18,
	ENEMYMERCHANT=19,
	PLATUC=20,
	SHIPEQUIP=21,
	FISH=22,
	ARENA=23,
	RANK=24,
	AWARD=25,
	TITLE=26,
	STARFATE=27,
	DAILY=28,
}

Packat_Account = {
	SEND_SOCKET_KEY = 0,
	REQUEST_REG_ACCOUNT = 1,
	ACCOUNT_REG_RESULT = 2,
	REQUEST_CREATE_CHAR = 3,
	REQUEST_LOGIN = 4,
	CHREATE_CHAR_RESULT=5,
	LOGIN_RESULT = 6,
	PLAYER_INFO = 7,
	REQUEST_JOIN = 8,
	REQUEST_LOGIN_TO_ACCSERVER = 9,
	REQUEST_REG_TO_ACCSERVER = 10,
	LOGIN_RLT_FROM_ACCSERVER = 11,
	REG_RLT_FROM_ACCSERVER = 12,
	ACCOUNT_ALREADY_LOGIN = 13,
}

Packat_Chat = {
	SERVER_MSG = 0,
	CLIENT_SEND_MSG = 1,
	SEND_CHAT_MSG = 2,
	SEND_HOME_CHAT_MSG = 3,
	SERVER_NOTICE_MSG = 4,
}

Packat_Player = {
	JOIN_MAP = 0,
	SYNCPLAYER = 1,
	CLIENT_SET_POS = 2,
	CLIENT_MOVE_TO = 3,
	SEND_PLAYER_INFO = 4,
	CLIENT_STOP=5,
	PLAYER_SELF_LEAVE_GAME=6,
	DISAPPEAR=7,
	CLIENT_REQUEST_JUMP=8,
	SEND_GIVE_GOLD_TIME=9,
	PLAYER_RUN_AWAY=10,
	CLIENT_REQUEST_START_BATTLE=11,
	CLIENT_REQUEST_JOIN_BATTLE=12,
	SEND_ATTACK=13,
	SEND_ATTACK_TO_OTHER=14,
	SYNCBATTLEPLAYER=15,
	SEND_MONEY=16,
	SEND_GOLD=17,
	SEND_LEVEL=18,
	SEND_EXP=19,
	CLIENT_REQUEST_ENTER_PORTAL=20,
	SEND_PLAYER_STOP=21,
	SERVER_FORCE_SET_CLIENT_POS=22,
	SEND_BATTLE_END=23,
	CLIENT_REPLY_FORCE_POS=24,
	CLIENT_REPLY_JOIN_MAP=25,
	SEND_CHG_SPEED=26,
	CLIENT_VIEW_OTHER_PLAYER_INFO = 27,
	SEND_OTHER_PLAYER_INFO = 28,
	SEND_PLAYER_CHG_JOB = 29,
	SEND_PLAYER_VIGOR = 30,
	SEND_PLAYER_VIGOR_BUY_COUNT = 31,
	CLIENT_REQUEST_BUY_VIGOR = 32,
	CLIENT_GET_TEST_GOLD = 33,
	CLIENT_REQUEST_LEAVE_BATTLE = 34,
	SEND_PLAYER_SYNC_OUT_OF_VIEW = 35,
	PLAT_FILL_MONEY = 36,
	SPEED_UP_CHECK = 37,
	GM_GIVE_GOLD = 38,
	SYNC_FAKE_PLAYER = 39,
	
	CLIENT_REQUEST_DRINK=40,
	SEND_SERVER_TIME=41,
	SEND_LEVEL_AWARD_INFO=42, -- 成长礼包信息
	CLIENT_REQUEST_GET_LEVEL_AWARD=43,
	SEND_DRINK_INFO=44,
	
	SEND_VIP_LEVEL=45,
	SEND_FIRST_FILL_MONEY=46,
	SEND_TOTAL_FILL_MONEY=47,
	SEND_SERVER_START_TIME=48,
	
	SEND_FIRST_EMPLOY_ORANGE=49,
	
	SEND_PROTECT_TIME=50,
	SEND_PROTECT_STATE=51,
	
	CLIENT_CRASH_REPORT=52,
	
	SEND_PLAYER_DEAD=53,
	
	SEND_BOSS_DMG_RANK=54,
	
	SEND_TOTAL_COST_GOLD = 55,
	SEND_MONEY_POT_USE_COUNT = 56,
	
	CLIENT_REQUEST_CHOOSE_MODE = 57,
	SEND_PLAYER_MODE_CHG = 58,
	
	CLIENT_ONLINE_PING = 59,
	
	SEND_BONUS_GOODS = 60,
	
	CLIENT_SEND_SERVER_TIME = 61,
	SEND_CLIENT_SPEED_UP_WARNDING = 62,
	
	CLIENT_SEND_PASSMAP_INDEX = 63,
	
	CLIENT_REQUEST_CHG_NAME = 64,

	SERVER_CHG_NAME = 65,
	SEND_CHG_NAME_FAILED = 66,
	SEND_CHG_NAME_SUC = 67,
	
	CLIENT_REQUEST_GIVE_ITEM_TO_GLOBAL = 68,
	SEND_GLOBAL_MISSION_STATE = 69,
	CLIENT_REQUEST_GLOBAL_MISSION_STATE = 70,
	SEND_GLOBAL_MISSION_DATA_CHG = 71,
	SEND_GLOBAL_MISSION_ADD = 72,
	SEND_GLOBAL_MISSION_END = 73,
	
	SEND_SKILL_ORB_POINT = 74,
	
	REQUEST_IOS_ADD_BILL = 75,

	SERVER_REQUEST_IOS_ADD_BILL = 76,
	SEND_IOS_BILL_END = 77,
	
	SEND_TRANSFER_REQUEST = 78,
	CLIENT_CONFIRM_TRANSFER = 79,

	CLIENT_SEND_BUY_MONEY = 80,
	
	SEND_CHG_POWER = 81,	
	
	CLIENT_SEND_BATTLE_COMMAND = 82,
	
	SEND_FISH_INFO = 83,
	SEND_GAME_INFO = 84,
	REQUEST_BUY_LEVEL_AWARD = 85,
	SEND_LEVEL_AWARD = 86, -- 成长礼包购买
	REQUEST_MONTH_AWARD = 87, -- 领取月卡奖励
	SEND_MONTH_CARD = 88, -- 月卡信息
}

Packat_Harbor = {
	CLIENT_REQUEST_ENTER_HARBOR = 0,
	SEND_ENTER_HARBOR = 1,
	CLIENT_REQUEST_LEAVE_HARBOR = 2,
	CLIENT_REQUEST_HARBOR_INFO = 3,
	SEND_HARBOR_INFO = 4,
	CLIENT_REQUEST_UP_MAIN_BUILDING = 5,
	CLIENT_REQUEST_UP_SHIP_FAC = 6,
	CLIENT_REQUEST_UP_SHOP = 7,
	CLIENT_REQUEST_UP_LAB = 8,
	SEND_MAIN_BUILDING_INFO = 9,
	SEND_SHIP_FAC_INFO = 10,
	SEND_SHOP_INFO = 11,
	SEND_LAB_INFO = 12,
	CLIENT_REQUEST_FAST_MAIN_UP=13,
	CLIENT_REQUEST_FAST_SHIP_UP=14,
	CLIENT_REQUEST_FAST_SHOP_UP=15,
	CLIENT_REQUEST_FAST_LAB_UP=16,
	SYNC_BATTLE_HARBOR=17,
	
	CLIENT_GET_SIGNUP_INFO=18,
	CLIENT_CLOSE_SIGNUP_FORM=19,
	CLIENT_REQUEST_SIGNUP=20,

	SEND_ALL_SIGNUP_INFO=21,
	SEND_SIGNUP_INFO=22,
	
	SERVER_REQUEST_SIGNUP=23,
	
	SEND_ALL_HARBORS_BELONG_YOU=24,

	SERVER_REQUEST_PUBLIC_HARBOR=25,
	
	SEND_REFRESH_HARBOR_INFO=26,
	
	CLIENT_REQUEST_HARBORWAR_STATE=27,
	SEND_HARBORWAR_STATE=28,
	
	SEND_HARBOR_TREASURE_STATE=29,
	CLIENT_REQUEST_GET_HARBOR_TREASURE=30,
	SERVER_REQUEST_HARBOR_TREASURE=31,
	
	SEND_ADD_HARBOR_BELONG_YOU = 32,
	SEND_DEL_HARBOR_BELONG_YOU = 33,
	
	SERVER_UP_BUILDING = 34,
	SERVER_REQUEST_HARBOR_INFO = 35,
	
	CLIENT_REQUEST_CANCEL_SIGNUP = 36,
	SERVER_REQUEST_CANCEL_SIGNUP = 37,
	SERVER_GET_SIGNUP_INFO = 38,
	SEND_HARBORWAR_SIGN_RLT = 39,
	
	SEND_HARBOR_PLAYERNAME_CHG = 40,

	CLIENT_REQUEST_SPECIAL_UP_BUILDING = 41,
}

Packat_Sailor = {
	CLIENT_REQUEST_EMPLOY_SAILOR = 0,
	SEND_FREE_EMPLOY_INFO = 1,
	SEND_ALREADY_HAVE_SAILOR = 2,
	SEND_ALL_SAILORS = 3,
	SEND_ADD_SAILOR = 4,
	SEND_DEL_SAILOR = 5,
	CLIENT_REQUEST_SET_SAILOR_DUTY = 6,
	SEND_SAILOR_CHG_DUTY = 7,
	SEND_EMPLOY_SAILOR_SUC = 8,
	CLIENT_REQUEST_TEMP_EMPLOY_SAILOR_INFO = 9,
	CLIENT_REQUEST_FIRE_SAILOR = 10,
	SEND_ALL_MERCHANT_SAILORS = 11,
	CLIENT_REQUEST_STAR_UP_SAILOR = 12,
	SEND_SAILOR_STAR_INFO = 13,
	CLIENT_REQUEST_EXCHANGE_SAILOR = 14,
	SEND_EXCHANGE_SAILOR = 15,
	SERVER_REQUEST_EXCHANGE_SAILOR = 16,
	CLIENT_REQUEST_EXCHANGELIST = 17,
	SERVER_REQUEST_EXCHANGELIST = 18,
	SERVER_REFRESH_EXSAILOR = 19,
	CLIENT_REQUEST_EXLEVEL_UP_SAILOR = 20,
	SEND_SAILOR_EXLEVEL_INFO = 21,
}

Packat_Goods = {
	SEND_ALL_GOODS = 0,
	CLIENT_BUY_GOODS = 1,
	CLINET_SELL_GOODS = 2,
	SEND_ADD_GOODS = 3,
	SEND_DEL_GOODS = 4,
	CLIENT_FULL_BUY_GOODS = 5,
	CLIENT_FULL_SELL_GOODS = 6,
	CLIENT_REQUEST_GOODS_PRICE = 7,
	SEND_GOODS_PRICE = 8,
	
	SEND_GOODS_POPULAR = 9,
	SEND_DEL_All_GOODS = 10,
}

Packat_Ship = {
	SEND_ALL_SHIP = 0,
	SEND_ADD_SHIP = 1,
	SEND_DEL_SHIP = 2,
	
	SEND_SHIP_BUILD_INFO = 3,
	SEND_SHIP_BUILD_TIME = 4,
	SEND_ADD_SHIP_BUILD = 5,
	SEND_DEL_SHIP_BUILD = 6,
	SEND_SHIP_BUILD_FINISH = 7,

	CLIENT_REQUEST_ADD_BUILD = 8,
	CLIENT_REQUEST_DEL_BUILD = 9,
	CLIENT_REQUEST_BUILD_INFO = 10,
	CLIENT_REQUEST_FAST_FINISH = 11,
	
	CLIENT_REQUEST_SET_SHIP_BATTLE = 12,
	CLIENT_REQUEST_SET_SHIP_STANDBY = 13,
	SEND_SHIP_SLOT = 14,
	CLIENT_REQUEST_DEL_SHIP = 15,
	SEND_ALL_MERCHANT_SHIP = 16,
	
	SEND_SHIP_LIFE = 17,
	
	SEND_SHIP_DESTROY = 18,
	
	SEND_SHIP_HP_CHG = 19,
	
	SEND_ADD_SHIP_EFFECT = 20,
	SEND_DEL_SHIP_EFFECT = 21,
	
	SEND_DEL_ALL_HARBOR_SHIP_BUILD = 22,
}

Packat_Lab = {
	SEND_ALL_RESEARCH = 0,
	CLIENT_REQUEST_RESEARCH = 1,
	SEND_RESEARCH_FINISH = 2,
	SEND_ADD_RESEARCH = 3,
	CLIENT_REQUEST_RESEARCH_FAST_FINISH = 4,
	SEND_DEL_ALL_HARBOR_RESEARCH = 5,
	CLIENT_SPECIAL_UP_RESEARCH = 6,
}

Packat_Skill = {
	SEND_ALL_SKILL = 0,
	SEND_ADD_SKILL = 1,
}

Packat_Equip = {
	SEND_ALL_EQUIP = 0,
	SEND_ADD_EQUIP = 1,
	CLIENT_PUT_ON_EQUIP = 2,
	CLIENT_TAKE_OFF_EQUIP = 3,
	SEND_EQUIP_SAILOR_CHANGE = 4,
	CLIENT_REQUEST_STAR_UP = 5,
	SEND_STAR_UP_RLT = 6,
	CLIENT_REQUEST_SPLIT = 7,
	SEND_DEL_EQUIP = 8,
	CLIENT_REQUEST_MAGIC_ITEM = 9,
	SEND_MAGIC_RLT = 10,
}

Packat_Enemy = {
	SYNCENEMY=0,
	ENEMY_MOVE_TO=1,
	ENEMY_DISAPPEAR=2,
	SEND_ENEMY_ATTACK=3,
	SEND_ENEMY_STOP=4,
	SEND_ENEMY_SYNC_OUT_OF_VIEW=5,
	SYNC_FAKE_ENEMY=6,
	
	ENEMY_SUPER_ATTACK=7,
	SEND_ENEMY_SUPER_ATTACK_TIME=8,
	SEND_ENEMY_SUPER_ATTACK_END=9,
	SEND_BOSS_INFO=10,
}

Packat_Battle = {
	SYNC_BATTLE_FIELD = 0,
	SEND_BATTLE_FIELD_ADD_OBJ = 1,
	SEND_BATTLE_FIELD_DEL_OBJ = 2,
	SEND_DEL_BATTLE_FIELD = 3,
	SEND_BATTLE_FILED_OUT_VIEW = 4,
}

Packat_Item = {
	SEND_ALL_ITEM = 0,
	SEND_ADD_ITEM = 1,
	CLIENT_REQUEST_DELETE_ITEM = 2,
	SEND_DEL_ITEM = 3,
	SEND_ITEM_COUNT_CHG = 4,
	CLIENT_REQUEST_USE_ITEM = 5,
	SEND_TURNTABLE_RLT = 6,
	SEND_CHEST_RLT = 7,
	
	SEND_TREASURE_MAP_RLT = 8,
	CLIENT_REQUEST_OPEN_TREASURE = 9,
	
	SEND_ALL_GIFTS = 10,
	CLIENT_REQUEST_GET_GIFTS = 11,
	SEND_ADD_GIFTS = 12,
	SEND_DEL_GIFTS = 13,
	SEND_GIFTS_CHG = 14,
	
	CLIENT_REQUEST_MULTI_USE_CHEST = 15,
	
	CLIENT_REQUEST_SERIAL = 16,

	SERVER_REQUEST_SERIAL = 17,
	
	SEND_GIFTS_USED = 18,
	
	CLIENT_REQUEST_BUY_ITEM = 19,
	CLIENT_TURN_TABLE_STOP = 20,
	
	
	SEND_ALL_LIMIT_BUY_ITEM = 21,
	SEND_ADD_LIMIT_BUY_ITEM = 22,
	SEND_LIMIT_BUY_ITEM_COUNT = 23,
	
	SEND_SPLIT_RLT = 24,
	
	CLIENT_REQUEST_EXCHANGE_ITEM = 25,
	
	SEND_BOSS_ROLL_AWARD = 26,
	CLIENT_REQUEST_ROLL = 27,
	
	SEND_ROLL_RLT = 28,
	
	CLIENT_REQUEST_GOLDGET_TREASURE = 29,
}

Packat_Relation = {
	SEND_ALL_RELATION = 0,
	SEND_ADD_RELATION = 1,
	CLIENT_REQUEST_ADD_FRIEND = 2,
	CLIENT_CONFIRM_ADD_FRIEND = 3,
	SEND_ASK_FOR_FRIEND = 4,
	INSERVER_OTHER_CONFIRM_FRIEND = 5,
	CLIENT_REQUEST_ADD_FRIEND_BY_UIN = 6,
	REQUEST_ADD_FRIEND_EXIST = 7,
	INSERVER_NOTIFY_FRIENDS = 8,
	INSERVER_REPLY_NOTIFY_FRIENDS = 9,
	CLIENT_REQUEST_ONLINE_FRIENDS_DETAIL = 10,
	SEND_ONLINE_FRIENDS_DETAIL = 11,
	CLIENT_REQUEST_DEL_FRIEND = 12,
	SEND_DEL_FRIEND = 13,
	
	CLIENT_REQUEST_LOCATE_ENEMY = 14,
	SEND_ENEMY_LOCATION = 15,
	CLIENT_REQUEST_JUMP_FIGHT_ENEMY = 16,
}

Packat_Family = {
	CLIENT_REQUEST_CREATE_HOME = 0,
	CLIENT_REQUEST_HOME_LIST = 1,
	CLIENT_REQUEST_JOIN_HOME = 2,
	CLIENT_REQUEST_ACCEPT_MEMBER = 3,
	CLIENT_REQUEST_KICK_MEMBER = 4,
	CLIENT_REQUEST_HOME_MEMBER_LIST = 5,
	CLIENT_REQUEST_HOME_JOIN_LIST = 6,
	SEND_HOME_TITLE = 7,
	SEND_DEL_HOME_TITLE = 8,
	SEND_HOME_INFO = 9,
	SEND_SIMPLE_HOME_LIST = 10,
	SEND_HOME_REQUEST_POSTED = 11,
	SEND_HOME_ADD_MEMBER = 12,
	SEND_HOME_DEL_MEMBER = 13,
	SEND_MEMBER_LIST = 14,
	SEND_JOIN_LIST = 15,
	SEND_CREATE_SUCCESSFUL = 16,
	SEND_HOME_MEMBER_ONLINE = 17,
	CLIENT_REQUEST_REFUSE_REQUEST = 18,
	SEND_REFUSE_REQUEST = 19,
	SEND_NEW_REQUEST = 20,
	CLIENT_REQUEST_LEAVE_HOME = 21,
	CLIENT_REQUEST_SET_HOME_DUTY = 22,
	CLIENT_REQUEST_GIVE_HOME_MONEY = 23,
	SEND_HOME_MEMBER_DUTY_CHG = 24,
	SEND_HOME_MONEY_CHG = 25,
	SEND_CONTRIBUTE_CHG = 26,
	CLIENT_REQUEST_CHG_NOTICE = 27,
	SEND_HOME_CHG_NOTICE = 28,
	CLIENT_REQUEST_LEVELUP_HOME = 29,
	SEND_HOME_LEVEL_CHG = 30,
	SEND_HOME_CHG_MASTER = 31,
	
	SEND_HOME_ITEM_LIST = 32,
	SEND_HOME_ITEM_COUNT = 33,

	CLIENT_REQUEST_BUY_HOME_ITEM = 34,

	CLIENT_REQUEST_HOME_ITEM_LIST = 35,
	CLIENT_CLOSE_HOME_ITEM_LIST = 36,
	
	CLIENT_REQUEST_GIVE_HOME_ITEM = 37,
	CLIENT_REQUEST_DEL_HOME_ITEM = 38,
	
	CLIENT_REQUEST_HOME_LOG = 39,
	SEND_HOME_LOG = 40,
}

Packat_CopyMap = {
	CLIENT_REQUEST_ENTER_INSTANCE = 0,
	SEND_FINISHED_INSTANCE = 1,
	SEND_INSTANCE_AWARD = 2,
	CLIENT_REQUEST_AUTO_FINISH_INSTANCE = 3,
	SEND_AUTO_INSTANCE_INFO = 4,
	CLIENT_REQUEST_FAST_AUTO_FINISH_INSTANCE = 5,
	SEND_ADD_FINISHED_INSTANCE = 6,
	SEND_NEW_ENEMY_ROUND = 7,
	
	SEND_BOSS_AWARD = 8,
	
	CLIENT_REQUEST_ENTER_TOWER = 9,
	SEND_TOWER_INFO = 10,

	SEND_TOWER_PASS_RLT = 11,

	SEND_TOWER_CHOOSE_BUFF = 12,
	CLIENT_CHOOSE_TOWER_BUFF = 13,
	
	CLIENT_FAST_FINISH_TOWER = 14,
}

Packat_Quest = {
	CLIENT_REQUEST_ADD_QUEST = 0,
	SEND_ADD_QUEST = 1,
	SEND_QUEST_FINISH = 2,
	SEND_QUEST_PARAM = 3,
	SEND_ALL_FINISHED_QUEST = 4,
	SEND_ALL_QUEST = 5,
	CLIENT_REQUEST_FINISH_QUEST = 6,
	CLIENT_REQUEST_ACCEPT_RANDOM_QUEST = 7,
	SEND_RANDOM_QUEST_INFO = 8,
	CLIENT_REQEUST_REFRESH_RANDOM_QUEST = 9,
	CLIENT_REQUEST_FAST_FINISH_RANDOM_QEUST = 10,
	CLIENT_REQUEST_GIVE_EQUIP = 11,
	CLIENT_REQUEST_GIVE_UP_RANDOM_QUEST = 12,
	SEND_DEL_QUEST = 13,
	SEND_FREE_REFRESH_RANDOM_QUEST_COUNT = 14,
}

Packat_Merchant = {
	CLIENT_REQUEST_ADD_MERCHANT = 0,
	SERVER_REQUEST_ADD_MERCHANT = 1,
	SYNC_MERCHANT = 2,
	CLIENT_REQUEST_DEL_MERCHANT=3,
	SERVER_REQUEST_DEL_MERCHANT=4,
	SERVER_DEL_MERCHANT_SELF=5,
	SEND_ALL_MERCHANT=6,
	SEND_ADD_MERCHANT=7,
	SEND_DEL_MERCHANT=8,
	CLIENT_REQUEST_CHG_MERCHANT_SAILOR=9,
	SEND_CHG_MERCHANT_SAILOR=10,
	CLIENT_REQUEST_CHG_MERCHANT_SHIP=11,
	SEND_CHG_MERCHANT_SHIP=12,
	CLIENT_REQUEST_MERCHANT_DETAIL=13,
	SEND_MERCHANT_DETAIL=14,
	SYNC_FAKE_MERCHANT=15,
	
	SERVER_REQUEST_CHG_MERCHANT_SAILOR=16,
	SERVER_REQUEST_CHG_MERCHANT_SHIP=17,
	SERVER_REQUEST_CHG_MASTER_LEVEL=18,
	SERVER_REQUEST_MERCHANT_DETAIL=19,

	SERVER_PLAYER_GET_MONEY=20,
	SERVER_MERCHANT_PLAYER__ONLINE=21,
	SEND_MERCHANT_SYNC_OUT_OF_VIEW=22,
	
	SERVER_RECYCLE_MERCHANT=23,
	
	SERVER_SEND_MERCHANT_MONEY=24,
}

Packat_Enemymerchant = {
	CLIENT_REQUEST_ATTACK_ENEMY_MERCHANT = 0,
	SEND_ENEMY_MERCHANT_CAN_REFRESH = 1,
	SEND_ALL_DEFEATED_ENEMY_MERCHANT = 2,
	SEND_ENEMY_MERCHANT_DEFEATED = 3,
}

Packat_UC = {
	UC_LOGIN = 0,
	UC_PAY = 0,
}

Packat_ShipEquip = {
	SEND_ALL_SHIP_EQUIP = 0,
	SEND_ADD_SHIP_EQUIP = 1,
	SEND_DEL_SHIP_EQUIP = 2,
	SEND_SHIP_EQUIP_SHIP_INDEX_CHG = 3,

	CLIENT_REQUEST_PUT_ON_SHIP_EQUIP = 4,
	CLIENT_REQUEST_TAKE_OFF_SHIP_EQUIP = 5,

	CLIENT_REQUEST_AUTO_EQUIP_SHIP = 6,
	CLIENT_REQUEST_UNEQUIP_SHIP = 7,
	
	CLIENT_REQUEST_STAR_UP_SHIP_EQUIP = 8,
	SEND_SHIP_EQUIP_STAR_INFO = 9,
	
	CLIENT_REQUEST_PROTECT_SHIP_EQUIP = 10,
	SEND_SHIP_EQUIP_PROTECT = 11,
}

Packat_Fish = {
	CLIENT_REQUEST_FISH_START = 0,
	SEND_FISH_START = 1,
	SEND_FISH_STOP = 2,
}

Packat_Rank = {
	CLIENT_REQUEST_RANK_PAGE=0,
	SEND_RANK_LIST=1,
	SERVER_REFRESH_RANK=2,
	SERVER_REFRESH_RANK_RLT=3,
	SERVER_REQUEST_RANK_PAGE=4,
	
	CLIENT_REQUEST_TOWER_RANK=5,
	SERVER_REQUEST_TOWER_RANK=6,
	SEND_TOWER_RANK_LIST=7,
	SERVER_CHECK_RANK_IN=8,
	
	CLIENT_REQUEST_TOWER_LASTRANK=9,
	SERVER_REQUEST_TOWER_LASTRANK=10,
	SEND_TOWER_LASTRANK_LIST=11,
	
	SERVER_CHECK_TOWER_TITLE=12,
}

Packat_Award = {
	SEND_LOGIN_AWARD_INFO = 0,
	CLIENT_REQUEST_GET_TODAY_AWARD = 1,
	
	SEND_DICE_ITEM_INFO=2,
	CLIENT_REQUEST_USE_DICE=3,
	SEND_GET_DICE_ITEM=4,
	CLIENT_DICE_STOP=5,

}

Packat_Title = {
	SEND_SET_TITLE = 0,
	SERVER_SET_TITLE = 1,
}

Packat_StarFate = {
	CLIENT_REQUEST_USE_SKILL = 0,

	SEND_ADD_SKILL_ORB = 1,
	SEND_DEL_SKILL_ORB = 2,
	SEND_ALL_SKILL_ORB = 3,

	SEND_SKILL_ORB_LEVELEXP = 4,

	CLIENT_REQUEST_DESTROY_ORB = 5,
	CLIENT_REQUEST_UPGRADE_ORB = 6,

	CLIENT_REQUEST_SET_ORB_IN_SLOT = 7,
	SEND_ORB_SLOT = 8,
	
	CLIENT_REQUEST_SET_BATTLE_SKILL=9,
	SEND_BATTLE_SKILL_TABLE=10,
	
	SEND_USE_BATTLE_SKILL_RLT=11,
	
	SEND_MAP_BUFF_LIST=12,
	SEND_MAP_ADD_BUFF=13,
	SEND_MAP_DEL_BUFF=14,

	SEND_RAGE_POINT=15,
	CLIENT_REQUEST_GET_TEMP_ORB=16,
	SEND_ORB_TEMP_STATE=17,

	CLIENT_REQUEST_HOROSCOPE=18,
	SEND_SCOPE_LEVEL=19,
	CLIENT_REQUEST_GET_ALL_TEMP=20,
	CLIENT_REQUEST_DES_ALL_TEMP=21,
	SEND_GET_ALL_TEMP_SUC=22,
	SEND_DES_ALL_TEMP_SUC=23,
	CLIENT_REQUEST_RMB_SCOPELEVEL=24,
	SEND_SCOPE_COUNT=25,
}

Packat_DAILY = {
	CLIENT_REQUEST_GET_AWARD = 0,
	SEND_ALL_DAILY = 1,
	SEND_ALL_DAILY_AWARD = 2,
}