-- id	:	技能ID
-- name	:	技能名称
-- cd	:	CD
-- mp	:	耗蓝量
-- range	:	范围
-- skill1icon	:	图标名称
-- active	:	是否主动
-- effect	:	特效
return {
	[1] = {
		["id"] = 1,
		["name"] = "技能1",
		["cd"] = 5,
		["mp"] = 25,
		["range"] = 100,
		["skill1icon"] = "skill1.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill1.prefab"},
	},
	[2] = {
		["id"] = 2,
		["name"] = "技能2",
		["cd"] = 6,
		["mp"] = 26,
		["range"] = 101,
		["skill1icon"] = "skill2.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill2.prefab"},
	},
	[3] = {
		["id"] = 3,
		["name"] = "技能3",
		["cd"] = 7,
		["mp"] = 27,
		["range"] = 102,
		["skill1icon"] = "skill3.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill3.prefab"},
	},
	[4] = {
		["id"] = 4,
		["name"] = "技能4",
		["cd"] = 8,
		["mp"] = 28,
		["range"] = 103,
		["skill1icon"] = "skill4.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill4.prefab"},
	},
	[5] = {
		["id"] = 5,
		["name"] = "技能5",
		["cd"] = 9,
		["mp"] = 29,
		["range"] = 104,
		["skill1icon"] = "skill5.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill5.prefab"},
	},
	[6] = {
		["id"] = 6,
		["name"] = "技能6",
		["cd"] = 10,
		["mp"] = 30,
		["range"] = 105,
		["skill1icon"] = "skill6.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill6.prefab"},
	},
	[7] = {
		["id"] = 7,
		["name"] = "技能7",
		["cd"] = 11,
		["mp"] = 31,
		["range"] = 106,
		["skill1icon"] = "skill7.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill7.prefab"},
	},
	[8] = {
		["id"] = 8,
		["name"] = "技能8",
		["cd"] = 12,
		["mp"] = 32,
		["range"] = 107,
		["skill1icon"] = "skill8.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill8.prefab"},
	},
	[9] = {
		["id"] = 9,
		["name"] = "技能9",
		["cd"] = 13,
		["mp"] = 33,
		["range"] = 108,
		["skill1icon"] = "skill9.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill9.prefab"},
	},
	[10] = {
		["id"] = 10,
		["name"] = "技能10",
		["cd"] = 14,
		["mp"] = 34,
		["range"] = 109,
		["skill1icon"] = "skill10.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill10.prefab"},
	},
	[11] = {
		["id"] = 11,
		["name"] = "技能11",
		["cd"] = 15,
		["mp"] = 35,
		["range"] = 110,
		["skill1icon"] = "skill11.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill11.prefab"},
	},
	[12] = {
		["id"] = 12,
		["name"] = "技能12",
		["cd"] = 16,
		["mp"] = 36,
		["range"] = 111,
		["skill1icon"] = "skill12.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill12.prefab"},
	},
	[13] = {
		["id"] = 13,
		["name"] = "技能13",
		["cd"] = 17,
		["mp"] = 37,
		["range"] = 112,
		["skill1icon"] = "skill13.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill13.prefab"},
	},
	[14] = {
		["id"] = 14,
		["name"] = "技能14",
		["cd"] = 18,
		["mp"] = 38,
		["range"] = 113,
		["skill1icon"] = "skill14.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill14.prefab"},
	},
	[15] = {
		["id"] = 15,
		["name"] = "技能15",
		["cd"] = 19,
		["mp"] = 39,
		["range"] = 114,
		["skill1icon"] = "skill15.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill15.prefab"},
	},
	[16] = {
		["id"] = 16,
		["name"] = "技能16",
		["cd"] = 20,
		["mp"] = 40,
		["range"] = 115,
		["skill1icon"] = "skill16.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill16.prefab"},
	},
	[17] = {
		["id"] = 17,
		["name"] = "技能17",
		["cd"] = 21,
		["mp"] = 41,
		["range"] = 116,
		["skill1icon"] = "skill17.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill17.prefab"},
	},
	[18] = {
		["id"] = 18,
		["name"] = "技能18",
		["cd"] = 22,
		["mp"] = 42,
		["range"] = 117,
		["skill1icon"] = "skill18.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill18.prefab"},
	},
	[19] = {
		["id"] = 19,
		["name"] = "技能19",
		["cd"] = 23,
		["mp"] = 43,
		["range"] = 118,
		["skill1icon"] = "skill19.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill19.prefab"},
	},
	[20] = {
		["id"] = 20,
		["name"] = "技能20",
		["cd"] = 24,
		["mp"] = 44,
		["range"] = 119,
		["skill1icon"] = "skill20.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill20.prefab"},
	},
	[21] = {
		["id"] = 21,
		["name"] = "技能21",
		["cd"] = 25,
		["mp"] = 45,
		["range"] = 120,
		["skill1icon"] = "skill21.png",
		["active"] = true,
		["effect"] = {name = "闪现", path = "res/effects/skill21.prefab"},
	},
}