CFG_EquipSuit = {}
CFG_EquipSuit["1_1"] = {id = "1_1", suitId = 1, setName = "荡寇套装", propertyId = 10, propertyValue = 2, equipCount = 2, totalCount = 6, power = 24, }
CFG_EquipSuit["1_2"] = {id = "1_2", suitId = 1, setName = "荡寇套装", propertyId = 2, propertyValue = 4, equipCount = 4, totalCount = 6, power = 48, }
CFG_EquipSuit["1_3"] = {id = "1_3", suitId = 1, setName = "荡寇套装", propertyId = 14, propertyValue = 4, equipCount = 6, totalCount = 6, power = 24, }
CFG_EquipSuit["2_1"] = {id = "2_1", suitId = 2, setName = "拉奥孔套装", propertyId = 6, propertyValue = 6, equipCount = 2, totalCount = 6, power = 72, }
CFG_EquipSuit["2_2"] = {id = "2_2", suitId = 2, setName = "拉奥孔套装", propertyId = 4, propertyValue = 6, equipCount = 4, totalCount = 6, power = 72, }
CFG_EquipSuit["2_3"] = {id = "2_3", suitId = 2, setName = "拉奥孔套装", propertyId = 8, propertyValue = 6, equipCount = 6, totalCount = 6, power = 0, }
CFG_EquipSuit["3_1"] = {id = "3_1", suitId = 3, setName = "罗恩格林套装", propertyId = 12, propertyValue = 3, equipCount = 2, totalCount = 6, power = 72, }
CFG_EquipSuit["3_2"] = {id = "3_2", suitId = 3, setName = "罗恩格林套装", propertyId = 4, propertyValue = 6, equipCount = 4, totalCount = 6, power = 72, }
CFG_EquipSuit["3_3"] = {id = "3_3", suitId = 3, setName = "罗恩格林套装", propertyId = 16, propertyValue = 6, equipCount = 6, totalCount = 6, power = 72, }
CFG_EquipSuit["4_1"] = {id = "4_1", suitId = 4, setName = "萨拉丁套装", propertyId = 10, propertyValue = 3, equipCount = 2, totalCount = 6, power = 72, }
CFG_EquipSuit["4_2"] = {id = "4_2", suitId = 4, setName = "萨拉丁套装", propertyId = 2, propertyValue = 6, equipCount = 4, totalCount = 6, power = 72, }
CFG_EquipSuit["4_3"] = {id = "4_3", suitId = 4, setName = "萨拉丁套装", propertyId = 14, propertyValue = 6, equipCount = 6, totalCount = 6, power = 72, }
CFG_EquipSuit["5_1"] = {id = "5_1", suitId = 5, setName = "圣殿骑士套装", propertyId = 6, propertyValue = 8, equipCount = 2, totalCount = 6, power = 96, }
CFG_EquipSuit["5_2"] = {id = "5_2", suitId = 5, setName = "圣殿骑士套装", propertyId = 4, propertyValue = 8, equipCount = 4, totalCount = 6, power = 96, }
CFG_EquipSuit["5_3"] = {id = "5_3", suitId = 5, setName = "圣殿骑士套装", propertyId = 8, propertyValue = 8, equipCount = 6, totalCount = 6, power = 0, }
CFG_EquipSuit["6_1"] = {id = "6_1", suitId = 6, setName = "波斯王子套装", propertyId = 12, propertyValue = 4, equipCount = 2, totalCount = 6, power = 96, }
CFG_EquipSuit["6_2"] = {id = "6_2", suitId = 6, setName = "波斯王子套装", propertyId = 4, propertyValue = 8, equipCount = 4, totalCount = 6, power = 96, }
CFG_EquipSuit["6_3"] = {id = "6_3", suitId = 6, setName = "波斯王子套装", propertyId = 16, propertyValue = 8, equipCount = 6, totalCount = 6, power = 96, }
CFG_EquipSuit["7_1"] = {id = "7_1", suitId = 7, setName = "七海套装", propertyId = 10, propertyValue = 4, equipCount = 2, totalCount = 6, power = 96, }
CFG_EquipSuit["7_2"] = {id = "7_2", suitId = 7, setName = "七海套装", propertyId = 2, propertyValue = 8, equipCount = 4, totalCount = 6, power = 96, }
CFG_EquipSuit["7_3"] = {id = "7_3", suitId = 7, setName = "七海套装", propertyId = 14, propertyValue = 8, equipCount = 6, totalCount = 6, power = 96, }
CFG_EquipSuit["8_1"] = {id = "8_1", suitId = 8, setName = "恺撒大帝套装", propertyId = 6, propertyValue = 10, equipCount = 2, totalCount = 6, power = 120, }
CFG_EquipSuit["8_2"] = {id = "8_2", suitId = 8, setName = "恺撒大帝套装", propertyId = 4, propertyValue = 10, equipCount = 4, totalCount = 6, power = 120, }
CFG_EquipSuit["8_3"] = {id = "8_3", suitId = 8, setName = "恺撒大帝套装", propertyId = 8, propertyValue = 10, equipCount = 6, totalCount = 6, power = 0, }
CFG_EquipSuit["9_1"] = {id = "9_1", suitId = 9, setName = "赵子龙套装", propertyId = 12, propertyValue = 5, equipCount = 2, totalCount = 6, power = 120, }
CFG_EquipSuit["9_2"] = {id = "9_2", suitId = 9, setName = "赵子龙套装", propertyId = 4, propertyValue = 10, equipCount = 4, totalCount = 6, power = 120, }
CFG_EquipSuit["9_3"] = {id = "9_3", suitId = 9, setName = "赵子龙套装", propertyId = 16, propertyValue = 10, equipCount = 6, totalCount = 6, power = 120, }
CFG_EquipSuit["10_1"] = {id = "10_1", suitId = 10, setName = "亚历山大套装", propertyId = 10, propertyValue = 5, equipCount = 2, totalCount = 6, power = 120, }
CFG_EquipSuit["10_2"] = {id = "10_2", suitId = 10, setName = "亚历山大套装", propertyId = 2, propertyValue = 10, equipCount = 4, totalCount = 6, power = 120, }
CFG_EquipSuit["10_3"] = {id = "10_3", suitId = 10, setName = "亚历山大套装", propertyId = 14, propertyValue = 10, equipCount = 6, totalCount = 6, power = 120, }
CFG_EquipSuit["11_1"] = {id = "11_1", suitId = 11, setName = "海灵套装", propertyId = 6, propertyValue = 12, equipCount = 2, totalCount = 6, power = 144, }
CFG_EquipSuit["11_2"] = {id = "11_2", suitId = 11, setName = "海灵套装", propertyId = 4, propertyValue = 12, equipCount = 4, totalCount = 6, power = 144, }
CFG_EquipSuit["11_3"] = {id = "11_3", suitId = 11, setName = "海灵套装", propertyId = 8, propertyValue = 12, equipCount = 6, totalCount = 6, power = 0, }
CFG_EquipSuit["12_1"] = {id = "12_1", suitId = 12, setName = "战神套装", propertyId = 12, propertyValue = 6, equipCount = 2, totalCount = 6, power = 144, }
CFG_EquipSuit["12_2"] = {id = "12_2", suitId = 12, setName = "战神套装", propertyId = 4, propertyValue = 12, equipCount = 4, totalCount = 6, power = 144, }
CFG_EquipSuit["12_3"] = {id = "12_3", suitId = 12, setName = "战神套装", propertyId = 16, propertyValue = 12, equipCount = 6, totalCount = 6, power = 144, }
CFG_EquipSuit["13_1"] = {id = "13_1", suitId = 13, setName = "海神套装", propertyId = 10, propertyValue = 6, equipCount = 2, totalCount = 6, power = 144, }
CFG_EquipSuit["13_2"] = {id = "13_2", suitId = 13, setName = "海神套装", propertyId = 2, propertyValue = 12, equipCount = 4, totalCount = 6, power = 144, }
CFG_EquipSuit["13_3"] = {id = "13_3", suitId = 13, setName = "海神套装", propertyId = 14, propertyValue = 12, equipCount = 6, totalCount = 6, power = 144, }
CFG_EquipSuit["14_1"] = {id = "14_1", suitId = 14, setName = "专属武器", propertyId = 2, propertyValue = 5, equipCount = 1, totalCount = 1, power = 60, }
CFG_EquipSuit["14_2"] = {id = "14_2", suitId = 14, setName = "专属武器", propertyId = 4, propertyValue = 5, equipCount = 1, totalCount = 1, power = 60, }
CFG_EquipSuit["14_3"] = {id = "14_3", suitId = 14, setName = "专属武器", propertyId = 6, propertyValue = 5, equipCount = 1, totalCount = 1, power = 60, }
CFG_EquipSuit["15_1"] = {id = "15_1", suitId = 15, setName = "战争女神套装", propertyId = 10, propertyValue = 8, equipCount = 2, totalCount = 6, power = 180, }
CFG_EquipSuit["15_2"] = {id = "15_2", suitId = 15, setName = "战争女神套装", propertyId = 2, propertyValue = 15, equipCount = 4, totalCount = 6, power = 180, }
CFG_EquipSuit["15_3"] = {id = "15_3", suitId = 15, setName = "战争女神套装", propertyId = 14, propertyValue = 15, equipCount = 6, totalCount = 6, power = 180, }