CFG_star = {}
CFG_star[1] = {id = 1, type = 1, name = "天枢", propertyId = 12, quality = 4, propertyValue = 4, starEnergy = 100, resId = "1", desc = "北斗七星第一星，又名贪狼星。", power = 60, key = "1000", }
CFG_star[2] = {id = 2, type = 2, name = "天璇", propertyId = 3, quality = 4, propertyValue = 1000, starEnergy = 100, resId = "2", desc = "北斗七星第二星，又名巨门星。", power = 300, key = "2000", }
CFG_star[3] = {id = 3, type = 3, name = "天玑", propertyId = 5, quality = 4, propertyValue = 3600, starEnergy = 100, resId = "3", desc = "北斗七星第三星，又名禄存星。", power = 270, key = "3000", }
CFG_star[4] = {id = 4, type = 4, name = "天权", propertyId = 10, quality = 4, propertyValue = 4, starEnergy = 100, resId = "4", desc = "北斗七星第四星，又名文曲星。", power = 60, key = "4000", }
CFG_star[5] = {id = 5, type = 5, name = "玉衡", propertyId = 16, quality = 4, propertyValue = 4, starEnergy = 100, resId = "5", desc = "北斗七星第五星，又名廉贞星。", power = 60, key = "5000", }
CFG_star[6] = {id = 6, type = 6, name = "开阳", propertyId = 1, quality = 4, propertyValue = 1000, starEnergy = 100, resId = "6", desc = "北斗七星第六星，又名武曲星。", power = 540, key = "6000", }
CFG_star[7] = {id = 7, type = 7, name = "摇光", propertyId = 14, quality = 4, propertyValue = 4, starEnergy = 100, resId = "7", desc = "北斗七星第七星，又名破军星。", power = 60, key = "7000", }
CFG_star[8] = {id = 8, type = 1, name = "天枢", propertyId = 12, quality = 3, propertyValue = 3, starEnergy = 50, resId = "8", desc = "北斗七星第一星，又名贪狼星。", power = 45, key = "100", }
CFG_star[9] = {id = 9, type = 2, name = "天璇", propertyId = 3, quality = 3, propertyValue = 500, starEnergy = 50, resId = "9", desc = "北斗七星第二星，又名巨门星。", power = 150, key = "200", }
CFG_star[10] = {id = 10, type = 3, name = "天玑", propertyId = 5, quality = 3, propertyValue = 1800, starEnergy = 50, resId = "10", desc = "北斗七星第三星，又名禄存星。", power = 135, key = "300", }
CFG_star[11] = {id = 11, type = 4, name = "天权", propertyId = 10, quality = 3, propertyValue = 3, starEnergy = 50, resId = "11", desc = "北斗七星第四星，又名文曲星。", power = 45, key = "400", }
CFG_star[12] = {id = 12, type = 5, name = "玉衡", propertyId = 16, quality = 3, propertyValue = 3, starEnergy = 50, resId = "12", desc = "北斗七星第五星，又名廉贞星。", power = 45, key = "500", }
CFG_star[13] = {id = 13, type = 6, name = "开阳", propertyId = 1, quality = 3, propertyValue = 500, starEnergy = 50, resId = "13", desc = "北斗七星第六星，又名武曲星。", power = 270, key = "600", }
CFG_star[14] = {id = 14, type = 7, name = "摇光", propertyId = 14, quality = 3, propertyValue = 3, starEnergy = 50, resId = "14", desc = "北斗七星第七星，又名破军星。", power = 45, key = "700", }
CFG_star[15] = {id = 15, type = 1, name = "天枢", propertyId = 12, quality = 2, propertyValue = 2, starEnergy = 6, resId = "15", desc = "北斗七星第一星，又名贪狼星。", power = 30, key = "10", }
CFG_star[16] = {id = 16, type = 2, name = "天璇", propertyId = 3, quality = 2, propertyValue = 250, starEnergy = 6, resId = "16", desc = "北斗七星第二星，又名巨门星。", power = 75, key = "20", }
CFG_star[17] = {id = 17, type = 3, name = "天玑", propertyId = 5, quality = 2, propertyValue = 900, starEnergy = 6, resId = "17", desc = "北斗七星第三星，又名禄存星。", power = 68, key = "30", }
CFG_star[18] = {id = 18, type = 4, name = "天权", propertyId = 10, quality = 2, propertyValue = 2, starEnergy = 6, resId = "18", desc = "北斗七星第四星，又名文曲星。", power = 30, key = "40", }
CFG_star[19] = {id = 19, type = 5, name = "玉衡", propertyId = 16, quality = 2, propertyValue = 2, starEnergy = 6, resId = "19", desc = "北斗七星第五星，又名廉贞星。", power = 30, key = "50", }
CFG_star[20] = {id = 20, type = 6, name = "开阳", propertyId = 1, quality = 2, propertyValue = 250, starEnergy = 6, resId = "20", desc = "北斗七星第六星，又名武曲星。", power = 135, key = "60", }
CFG_star[21] = {id = 21, type = 7, name = "摇光", propertyId = 14, quality = 2, propertyValue = 2, starEnergy = 6, resId = "21", desc = "北斗七星第七星，又名破军星。", power = 30, key = "70", }
CFG_star[22] = {id = 22, type = 1, name = "天枢", propertyId = 12, quality = 1, propertyValue = 1, starEnergy = 3, resId = "22", desc = "北斗七星第一星，又名贪狼星。", power = 15, key = "1", }
CFG_star[23] = {id = 23, type = 2, name = "天璇", propertyId = 3, quality = 1, propertyValue = 125, starEnergy = 3, resId = "23", desc = "北斗七星第二星，又名巨门星。", power = 38, key = "2", }
CFG_star[24] = {id = 24, type = 3, name = "天玑", propertyId = 5, quality = 1, propertyValue = 450, starEnergy = 3, resId = "24", desc = "北斗七星第三星，又名禄存星。", power = 34, key = "3", }
CFG_star[25] = {id = 25, type = 4, name = "天权", propertyId = 10, quality = 1, propertyValue = 1, starEnergy = 3, resId = "25", desc = "北斗七星第四星，又名文曲星。", power = 15, key = "4", }
CFG_star[26] = {id = 26, type = 5, name = "玉衡", propertyId = 16, quality = 1, propertyValue = 1, starEnergy = 3, resId = "26", desc = "北斗七星第五星，又名廉贞星。", power = 15, key = "5", }
CFG_star[27] = {id = 27, type = 6, name = "开阳", propertyId = 1, quality = 1, propertyValue = 125, starEnergy = 3, resId = "27", desc = "北斗七星第六星，又名武曲星。", power = 68, key = "6", }
CFG_star[28] = {id = 28, type = 7, name = "摇光", propertyId = 14, quality = 1, propertyValue = 1, starEnergy = 3, resId = "28", desc = "北斗七星第七星，又名破军星。", power = 15, key = "7", }