CFG_property = {}
CFG_property[1] = {id = 1, type = "攻击", sign = "", desc = "人物攻击增加", }
CFG_property[2] = {id = 2, type = "攻击加成", sign = "%", desc = "人物攻击百分比提升", }
CFG_property[3] = {id = 3, type = "防御", sign = "", desc = "人物防御增加", }
CFG_property[4] = {id = 4, type = "防御加成", sign = "%", desc = "人物防御百分比提升", }
CFG_property[5] = {id = 5, type = "生命", sign = "", desc = "人物hp增加", }
CFG_property[6] = {id = 6, type = "生命加成", sign = "%", desc = "人物hp百分比提升", }
CFG_property[7] = {id = 7, type = "贸易", sign = "", desc = "贸易增加", }
CFG_property[8] = {id = 8, type = "贸易加成", sign = "%", desc = "贸易百分比提升", }
CFG_property[9] = {id = 9, type = "命中", sign = "", desc = "命中提升", }
CFG_property[10] = {id = 10, type = "命中加成", sign = "%", desc = "命中率增加百分比", }
CFG_property[11] = {id = 11, type = "闪避", sign = "", desc = "闪避提升", }
CFG_property[12] = {id = 12, type = "闪避加成", sign = "%", desc = "闪避率增加百分比", }
CFG_property[13] = {id = 13, type = "暴击", sign = "", desc = "暴击提升", }
CFG_property[14] = {id = 14, type = "暴击加成", sign = "%", desc = "暴击率增加百分比", }
CFG_property[15] = {id = 15, type = "抗暴", sign = "", desc = "抗暴提升", }
CFG_property[16] = {id = 16, type = "抗暴加成", sign = "%", desc = "抗暴增加百分比", }
CFG_property[17] = {id = 17, type = "", sign = "", desc = "强化几率百分比提升", }
CFG_property[18] = {id = 18, type = "", sign = "", desc = "造船CD时间百分比减少", }
CFG_property[19] = {id = 19, type = "", sign = "", desc = "建筑物升级CD时间百分比减少", }
CFG_property[20] = {id = 20, type = "", sign = "", desc = "攻击港口时对港口伤害百分比提升", }
CFG_property[21] = {id = 21, type = "", sign = "", desc = "科技升级CD时间百分比减少", }
CFG_property[22] = {id = 22, type = "", sign = "", desc = "船攻击百分比提升", }
CFG_property[23] = {id = 23, type = "", sign = "", desc = "船防御均百分比提升", }
CFG_property[24] = {id = 24, type = "", sign = "", desc = "射程百分比提升", }
CFG_property[25] = {id = 25, type = "", sign = "", desc = "航速百分比提升", }
CFG_property[26] = {id = 26, type = "", sign = "", desc = "攻击时，攻击敌方剩余血量最少的船只", }
CFG_property[27] = {id = 27, type = "", sign = "", desc = "被攻击时，反弹自身所受伤害的百分比给攻击方", }
CFG_property[28] = {id = 28, type = "", sign = "", desc = "攻击敌方并有几率回复自身百分比血量", }
CFG_property[29] = {id = 29, type = "", sign = "", desc = "攻击敌方并有几率回复本方3个单位百分比的血量。", }
CFG_property[30] = {id = 30, type = "", sign = "", desc = "攻击时，有几率触发无敌状态，该状态可无视敌方进攻5秒。", }
CFG_property[31] = {id = 31, type = "", sign = "", desc = "攻击时，触发狂化状态，每次攻击损失自身血条5%血量致使敌方所受伤害百分比增加。", }
CFG_property[32] = {id = 32, type = "", sign = "", desc = "同时攻击3个目标，但百分比伤害降低。", }
CFG_property[33] = {id = 33, type = "", sign = "", desc = "攻击敌方并在接下来3秒钟内每秒附加1次本次伤害百分比的火焰伤害。", }
CFG_property[34] = {id = 34, type = "", sign = "", desc = "有几率消除敌方炮击后的持续火焰伤害。", }
CFG_property[35] = {id = 35, type = "", sign = "", desc = "攻击敌方并将敌方所受伤害的百分比转化为自身血量。", }
CFG_property[36] = {id = 36, type = "", sign = "", desc = "死亡时有几率进行自爆，对距离自己射程范围内所有单位进行无差别打击，造成的伤害按自爆船只血条的百分比计算。", }
CFG_property[37] = {id = 37, type = "", sign = "", desc = "与玩家PK时，船有几率不掉耐久。", }
CFG_property[38] = {id = 38, type = "", sign = "", desc = "船仓库增加", }
CFG_property[39] = {id = 39, type = "", sign = "", desc = "被击杀时，有几率原地百分比血量复活。", }
CFG_property[40] = {id = 40, type = "", sign = "", desc = "对方无敌状态对装备有本船首像的船只无效。", }
CFG_property[41] = {id = 41, type = "", sign = "", desc = "攻击时，随机对敌方一个单位进行1次雷击，伤害百分比增加。", }
CFG_property[42] = {id = 42, type = "伤害减免", sign = "%", desc = "减伤率百分比增加", }
CFG_property[43] = {id = 43, type = "伤害加成", sign = "%", desc = "伤害百分比提升", }
CFG_property[44] = {id = 44, type = "", sign = "", desc = "战斗获得的所有银两收益百分比增加", }
CFG_property[45] = {id = 45, type = "", sign = "", desc = "攻击时，有几率进行1次连击。", }
CFG_property[46] = {id = 46, type = "", sign = "", desc = "攻击时有几率附加当前银两十万分之一的伤害，每附加1点伤害需消耗1000银两。", }
CFG_property[47] = {id = 47, type = "", sign = "", desc = "战斗胜利时有几率从对方物品栏内随机偷取1件物品。", }
CFG_property[48] = {id = 48, type = "", sign = "", desc = "攻击敌方并使敌方航速百分比降低。", }
CFG_property[49] = {id = 49, type = "", sign = "", desc = "攻击敌方并获得天使圣光加持，使得自身攻击间隔百分比缩短。", }
CFG_property[50] = {id = 50, type = "", sign = "", desc = "攻击敌方并令对方中毒，使对方攻击间隔百分比延长。", }
CFG_property[51] = {id = 51, type = "", sign = "", desc = "给本方3个单位附加减伤率百分比提升的光环。", }
CFG_property[52] = {id = 52, type = "", sign = "", desc = "给本方3个单位附加暴击百分比提升的光环。", }
CFG_property[53] = {id = 53, type = "", sign = "", desc = "给本方3个单位附加伤害百分比提升的光环。", }
CFG_property[54] = {id = 54, type = "", sign = "", desc = "给本方3个单位附加闪避百分比提升的光环。", }
CFG_property[55] = {id = 55, type = "", sign = "", desc = "给本方3个单位附加命中百分比提升的光环。", }
CFG_property[56] = {id = 56, type = "", sign = "", desc = "给本方3个单位附加抗暴百分比提升的光环。", }
CFG_property[57] = {id = 57, type = "攻击", sign = "", desc = "船攻击增加", }
CFG_property[58] = {id = 58, type = "防御", sign = "", desc = "船防御增加", }
CFG_property[59] = {id = 59, type = "船速", sign = "", desc = "船速增加", }
CFG_property[60] = {id = 60, type = "生命", sign = "", desc = "船血量增加", }
CFG_property[61] = {id = 61, type = "", sign = "", desc = "被打劫是保底XX银两", }
CFG_property[62] = {id = 62, type = "射程", sign = "", desc = "射程增加", }
CFG_property[63] = {id = 63, type = "射速", sign = "", desc = "射速增加", }
CFG_property[64] = {id = 64, type = "总生命", sign = "%", desc = "总生命百分比增加", }
CFG_property[65] = {id = 65, type = "怒气", sign = "", desc = "怒气增加", }
CFG_property[66] = {id = 66, type = "", sign = "", desc = "对敌方附加伤害值", }
CFG_property[67] = {id = 67, type = "", sign = "", desc = "3秒内增加攻击伤害值", }
CFG_property[68] = {id = 68, type = "", sign = "", desc = "回复生命值", }
CFG_property[69] = {id = 69, type = "", sign = "", desc = "使用该技能后己方3艘船生命共享", }
CFG_property[70] = {id = 70, type = "", sign = "", desc = "无敌时间增加", }