
AudioData = {
	business = {path="mp3/business", volumeScale=1},
	attack = {path="mp3/attack", volumeScale=1},
	battleSucc = {path="mp3/battleSucc", volumeScale=1},
	shoot = {path="mp3/shoot", volumeScale=0.65},
	bomb = {path="mp3/bomb", volumeScale=0.65},
	build = {path="mp3/build", volumeScale=1},
	click = {path="mp3/click", volumeScale=1},
	sink = {path="mp3/sink", volumeScale=1},
	levelUp = {path="mp3/levelUp", volumeScale=0.6},
	kaishi = {path="mp3/kaishi", volumeScale=1},
	hangxing = {path="mp3/hangxing", volumeScale=1},
	zhandou = {path="mp3/zhandou", volumeScale=1},
	gull1 = {path="mp3/gull/gull1", volumeScale=1},
	gull2 = {path="mp3/gull/gull2", volumeScale=1},
	gull3 = {path="mp3/gull/gull3", volumeScale=1},
	gull4 = {path="mp3/gull/gull4", volumeScale=1},
	gull5 = {path="mp3/gull/gull5", volumeScale=1},
	["1"] = {path="mp3/harbor/1", volumeScale=1},
	["2"] = {path="mp3/harbor/2", volumeScale=1},
	["3"] = {path="mp3/harbor/3", volumeScale=1},
	["4"] = {path="mp3/harbor/4", volumeScale=1},
	["5"] = {path="mp3/harbor/5", volumeScale=1},
	["6"] = {path="mp3/harbor/6", volumeScale=1},
	["7"] = {path="mp3/harbor/7", volumeScale=1},
	["8"] = {path="mp3/harbor/8", volumeScale=1},
	["9"] = {path="mp3/harbor/9", volumeScale=1},
	-- gull6 = {path="gull/gull6", volumeScale=1},
	-- gull7 = {path="gull/gull7", volumeScale=1},
	-- gull8 = {path="gull/gull8", volumeScale=1},
}

AudioSkill = {
	[2] = {path="mp3/skill/2", volumeScale=1},
	[3] = {path="mp3/skill/3", volumeScale=1},
	[5] = {path="mp3/skill/5", volumeScale=1},
	[7] = {path="mp3/skill/7", volumeScale=1},
	[8] = {path="mp3/skill/8", volumeScale=1},
	[9] = {path="mp3/skill/9", volumeScale=1},
	[10] = {path="mp3/skill/10", volumeScale=1},
	[11] = {path="mp3/skill/11", volumeScale=1},
	[12] = {path="mp3/skill/12", volumeScale=1},
	[13] = {path="mp3/skill/13", volumeScale=1},
	[14] = {path="mp3/skill/14", volumeScale=1},
}
