
--GUI按钮自定义style
GUIStyleButton = {
	CommandBtn = {	normal={background="Texture/Gui/Button/commandBtn",textColor=Color.Lime}, 
					active={background="Texture/Gui/Button/commandBtn",textColor=Color.Lime},
					fontSize=18,
					font = "font/art",
					alignment=TextAnchor.LowerCenter,},
	DailyBtn = {	normal={background="Texture/Gui/Button/dailyBtn_1"}, 
					active={background="Texture/Gui/Button/dailyBtn_2"},
					},
	InfoBtn = {	normal={background="Texture/Gui/Button/infoBtn_1"}, 
					active={background="Texture/Gui/Button/infoBtn_2"},
					},
	UpBtn = {	normal={background="Texture/Gui/Button/btn_up"}, 
					active={background="Texture/Gui/Button/btn_up"},
					},
	DownBtn = {	normal={background="Texture/Gui/Button/btn_down"}, 
					active={background="Texture/Gui/Button/btn_down"},
					},
	Quality_1_1 = {	normal={background="Texture/Gui/Button/quality_1"}, 
					active={background="Texture/Gui/Button/quality_2"},
					},
	Quality_1_2 = {	normal={background="Texture/Gui/Button/quality_2"}, 
					active={background="Texture/Gui/Button/quality_2"},
					},
	Quality_2_1 = {	normal={background="Texture/Gui/Button/quality_3"}, 
					active={background="Texture/Gui/Button/quality_4"},
					},
	Quality_2_2 = {	normal={background="Texture/Gui/Button/quality_4"}, 
					active={background="Texture/Gui/Button/quality_4"},
					},
	Quality_3_1 = {	normal={background="Texture/Gui/Button/quality_5"}, 
					active={background="Texture/Gui/Button/quality_6"},
					},
	Quality_3_2 = {	normal={background="Texture/Gui/Button/quality_6"}, 
					active={background="Texture/Gui/Button/quality_6"},
					},
	Quality_4_1 = {	normal={background="Texture/Gui/Button/quality_7"}, 
					active={background="Texture/Gui/Button/quality_8"},
					},
	Quality_4_2 = {	normal={background="Texture/Gui/Button/quality_8"}, 
					active={background="Texture/Gui/Button/quality_8"},
					},
	Btn_B = {	normal={background="Texture/Gui/Button/btn_d"}, 
					active={background="Texture/Gui/Button/btn_d"},
					},
					
	StarSkillListBtn = {	normal={background="Texture/Gui/Button/starSkillList_1"}, 
					active={background="Texture/Gui/Button/starSkillList_2"},},
	StarBreakBtn = {	normal={background="Texture/Gui/Button/starBreak_1"}, 
					active={background="Texture/Gui/Button/starBreak_2"},},
	StarTakeBtn = {	normal={background="Texture/Gui/Button/starTake_1"}, 
					active={background="Texture/Gui/Button/starTake_2"},},
	StarTakeBtn2 = {	normal={background="Texture/Gui/Button/starTake_3"}, 
					active={background="Texture/Gui/Button/starTake_4"},},
	ActivateBtn = {	normal={background="Texture/Gui/Button/activate_1"}, 
					active={background="Texture/Gui/Button/activate_2"},},
	StarGet1Btn = {	normal={background="Texture/Gui/Button/starGet_1"}, 
					active={background="Texture/Gui/Button/starGet_2"},
					},
	StarGet2Btn = {	normal={background="Texture/Gui/Button/starGet_3"}, 
					active={background="Texture/Gui/Button/starGet_4"},
					},
	StarGet3Btn = {	normal={background="Texture/Gui/Button/starGet_5"}, 
					active={background="Texture/Gui/Button/starGet_6"},
					},
	StarGet4Btn = {	normal={background="Texture/Gui/Button/starGet_7"}, 
					active={background="Texture/Gui/Button/starGet_8"},
					},
	StarGet1Btn2 = {	normal={background="Texture/Gui/Button/starGet_2"}, 
					active={background="Texture/Gui/Button/starGet_2"},
					},
	StarGet2Btn2 = {	normal={background="Texture/Gui/Button/starGet_4"}, 
					active={background="Texture/Gui/Button/starGet_4"},
					},
	StarGet3Btn2 = {	normal={background="Texture/Gui/Button/starGet_6"}, 
					active={background="Texture/Gui/Button/starGet_6"},
					},
	StarGet4Btn2 = {	normal={background="Texture/Gui/Button/starGet_8"}, 
					active={background="Texture/Gui/Button/starGet_8"},
					},
	StarBgBtn = {	normal={background="Texture/Gui/Button/starBg_1"}, 
					active={background="Texture/Gui/Button/starBg_2"},},
	StarBgBtn2 = {	normal={background="Texture/Gui/Button/starBg_3"}, 
					active={background="Texture/Gui/Button/starBg_4"},},
	StarSkillBtn = {	normal={background="Texture/Gui/Button/starSkill_1"}, 
					active={background="Texture/Gui/Button/starSkill_2"},},
	StarSkillBtn2 = {	normal={background="Texture/Gui/Button/starSkill_3"}, 
					active={background="Texture/Gui/Button/starSkill_4"},},
	OkBtn = {	normal={background="Texture/Gui/Button/ok_1"}, 
					active={background="Texture/Gui/Button/ok_2"},},
	CancelBtn_2 = {	normal={background="Texture/Gui/Button/cancel_3"}, 
					active={background="Texture/Gui/Button/cancel_4"},},
	RollBtn = {	normal={background="Texture/Gui/Button/btn22_1"}, 
					active={background="Texture/Gui/Button/btn22_2"},},
	GiveUpBtn_1 = {	normal={background="Texture/Gui/Button/btn21_1"}, 
					active={background="Texture/Gui/Button/btn21_2"},},
	PassBtn_1 = {	normal={background="Texture/Gui/Button/pass_3"}, 
					active={background="Texture/Gui/Button/pass_4"},},
	PassBtn_2 = {	normal={background="Texture/Gui/Button/pass_5"}, 
					active={background="Texture/Gui/Button/pass_6"},},
	PassBtn_3 = {	normal={background="Texture/Gui/Button/pass_7"}, 
					active={background="Texture/Gui/Button/pass_8"},},
	PassBtn_4 = {	normal={background="Texture/Gui/Button/pass_9"}, 
					active={background="Texture/Gui/Button/pass_10"},},
	-- PassBtn_5 = {	normal={background="Texture/Gui/Button/pass_11"}, 
					-- active={background="Texture/Gui/Button/pass_12"},},
	PassBtn_6 = {	normal={background="Texture/Gui/Button/pass_13"}, 
					active={background="Texture/Gui/Button/pass_14"},},
	PassBtn = {	normal={background="Texture/Gui/Button/pass_1"}, 
					active={background="Texture/Gui/Button/pass_2"},},
	MagicBtn = {	normal={background="Texture/Gui/Button/magicBtn_1"}, 
					active={background="Texture/Gui/Button/magicBtn_2"},},
	ShowBtn_1 = {	normal={background="Texture/Gui/Button/showBtn_1"}, 
					active={background="Texture/Gui/Button/showBtn_2"},},
	ShowBtn_2 = {	normal={background="Texture/Gui/Button/showBtn_3"}, 
					active={background="Texture/Gui/Button/showBtn_4"},},
	ShowBtn_3 = {	normal={background="Texture/Gui/Button/showBtn_5"}, 
					active={background="Texture/Gui/Button/showBtn_6"},},
	ShowBtn_4 = {	normal={background="Texture/Gui/Button/showBtn_7"}, 
					active={background="Texture/Gui/Button/showBtn_8"},},
	ShowBtn_5 = {	normal={background="Texture/Gui/Button/showBtn_9"}, 
					active={background="Texture/Gui/Button/showBtn_10"},},
	ShowBtn_6 = {	normal={background="Texture/Gui/Button/showBtn_11"}, 
					active={background="Texture/Gui/Button/showBtn_12"},},
					
	VipButton = {	normal={background="Texture/Gui/Button/vipBtn_1"}, 
					active={background="Texture/Gui/Button/vipBtn_2"},},
	StartButton = {	normal={background="Texture/Gui/Button/start_5"}, 
					active={background="Texture/Gui/Button/start_6"},},
	CloseButton = {	normal={background="Texture/Gui/Button/close_1"}, 
					active={background="Texture/Gui/Button/close_2"},},
	OpenButton = {	normal={background="Texture/Gui/Button/open_1"}, 
					active={background="Texture/Gui/Button/open_2"},},
	SignButton = {	normal={background="Texture/Gui/Button/sign_1"}, 
					active={background="Texture/Gui/Button/sign_2"},},
	LoginButton = {	normal={background="Texture/Gui/Button/login_1"}, 
					active={background="Texture/Gui/Button/login_2"},},
	ShowSelfHarbor = {	normal={background="Texture/Gui/Text/showSelfHarbor_1"}, 
					active={background="Texture/Gui/Text/showSelfHarbor_2"},},
	HideSelfHarbor = {	normal={background="Texture/Gui/Text/hideSelfHarbor_1"}, 
					active={background="Texture/Gui/Text/hideSelfHarbor_2"},},
	Rank = {	normal={background="Texture/Gui/Button/rank_1"}, 
					active={background="Texture/Gui/Button/rank_2"},},
	--boss挑战
	BossDuel = {	normal={background="Texture/Gui/Button/BossDuel_1"}, 
					active={background="Texture/Gui/Button/BossDuel_2"},},
	Mode1 = {	normal={background="Texture/Gui/Button/mode1"}, 
					active={background="Texture/Gui/Button/mode1"},},
	Mode2 = {	normal={background="Texture/Gui/Button/mode2"}, 
					active={background="Texture/Gui/Button/mode2"},},
	SelectMode = {	normal={background="Texture/Gui/Button/selectMode_1"}, 
					active={background="Texture/Gui/Button/selectMode_2"},},
	AutoSelect = {	normal={background="Texture/Gui/Button/autoSelect_1"}, 
					active={background="Texture/Gui/Button/autoSelect_2"},},
	AutoSelect_1 = {	normal={background="Texture/Gui/Button/autoSelect_3"}, 
					active={background="Texture/Gui/Button/autoSelect_4"},},
	SendButton = {	normal={background="Texture/send"}, 
					active={background="Texture/send"},
					Forever=true},
	BossAward = {	normal={background="Texture/Gui/Button/bossAward_1"}, 
					active={background="Texture/Gui/Button/bossAward_2"},},
	ViewBattle = {	normal={background="Texture/Gui/Button/viewBattle_1"}, 
					active={background="Texture/Gui/Button/viewBattle_1"},},
	ViewChar = {	normal={background="Texture/Gui/Button/viewChar_1"}, 
					active={background="Texture/Gui/Button/viewChar_1"},},
	Fish = {	normal={background="Texture/Gui/Button/fish_3"}, 
					active={background="Texture/Gui/Button/fish_4"},},
	BattleList = {	normal={background="Texture/Gui/Button/battleList_1"}, 
					active={background="Texture/Gui/Button/battleList_2"},},
	GetGold = {	normal={background="Texture/Gui/Button/getGold_1"}, 
					active={background="Texture/Gui/Button/getGold_2"},},
	GetGold_2 = {	normal={background="Texture/Gui/Button/getGold_2"}, 
					active={background="Texture/Gui/Button/getGold_2"},},
	First = {	normal={background="Texture/Gui/Button/first_1"}, 
					active={background="Texture/Gui/Button/first_2"},},
	Stop = {	normal={background="Texture/Gui/Button/stop_1"}, 
					active={background="Texture/Gui/Button/stop_2"},},
	Run = {	normal={background="Texture/Gui/Button/run_1"}, 
					active={background="Texture/Gui/Button/run_1"},},
	Take = {	normal={background="Texture/Gui/Button/take_1"}, 
					active={background="Texture/Gui/Button/take_2"},},
	PowerUp = {	normal={background="Texture/Gui/Button/powerUp_1"}, 
					active={background="Texture/Gui/Button/powerUp_2"},},
	Start_2 = {	normal={background="Texture/Gui/Button/start_3"}, 
					active={background="Texture/Gui/Button/start_4"},},
	Btn23 = {	normal={background="Texture/Gui/Button/btn23_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn23_1",textColor=Color.White},
					fontSize=18,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
	Transparent = {	normal={textColor=Color.White}, 
					active={textColor=Color.White},
					fontSize=25,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
	Transparent_Art = {	normal={textColor=Color.White}, 
					active={textColor=Color.White},
					fontSize=25,
					richText=true,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Transparent_20 = {	normal={textColor=Color.Blue}, 
					active={background="Texture/Gui/empty",textColor=Color.Blue},
					fontSize=20,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
					
					
	Link_25 = {	normal={textColor=Color.LinkBlue}, 
		active={background="Texture/Gui/empty",textColor=Color.LinkRed},
		fontSize=25,
		richText=true,
		alignment=TextAnchor.MiddleCenter,},		
					
					
					
			
	Transparent_Art_25 = {	normal={textColor=Color.LightBlue}, 
					active={background="Texture/Gui/empty",textColor=Color.Lime},
					fontSize=25,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Transparent_Art_25_Lime = {	normal={textColor=Color.Lime}, 
					active={background="Texture/Gui/empty",textColor=Color.LightBlue},
					fontSize=25,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Transparent_Art_30 = {	normal={textColor=Color.LightBlue}, 
					active={background="Texture/Gui/empty",textColor=Color.Lime},
					fontSize=30,
					richText=true,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Transparent_30_Brown_Art = {normal={textColor=Color.Brown}, 
					active={textColor=Color.Brown},
					fontSize=30,
					-- font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Transparent_40_Art = {	normal={textColor=Color.White}, 
					active={textColor=Color.White},
					fontSize=40,
					richText=true,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	Select_35_Art = {normal={background="Texture/Gui/Bg/bg50_2", textColor=Color.Lime}, 
					active={background="Texture/Gui/Bg/bg50_2", textColor=Color.Lime},
					fontSize=30,
					richText=true,
					font = "font/art",
					padding={top=3},
					alignment=TextAnchor.MiddleCenter,},
	-- START = {		normal={background="Texture/Gui/Button/join1",textColor=Color.White}, 
					-- active={background="Texture/Gui/Button/join2",textColor=Color.White},
					-- fontSize=ConstValue.DefaultFontSize,
					-- richText=true,
					-- alignment=TextAnchor.UpperCenter,},
	OrangeBtn = {	normal={background="Texture/Gui/Button/btn1_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn1_2",textColor=Color.White},
					fontSize=35,
					richText=true,
					font = "font/art",
					padding={top=17},
					alignment=TextAnchor.UpperCenter,},
	OrangeBtn_25_Yellow = {	normal={background="Texture/Gui/Button/btn1_1",textColor=Color.Yellow}, 
					active={background="Texture/Gui/Button/btn1_2",textColor=Color.Yellow},
					fontSize=25,
					richText=true,
					font = "font/art",
					padding={top=8},
					alignment=TextAnchor.UpperCenter,},
	OrangeBtn_2 = {	normal={background="Texture/Gui/Button/btn18_1"}, 
					active={background="Texture/Gui/Button/btn18_2"},},
	OrangeBtn_3 = {	normal={background="Texture/Gui/Button/btn18_1",textColor=Color.LightYellow}, 
					active={background="Texture/Gui/Button/btn18_2",textColor=Color.Brown3},
					fontSize=33,
					font = "font/art",
					padding={top=5},
					alignment=TextAnchor.MiddleCenter,},
	ChangeShipBtn = {	normal={background="Texture/Gui/Button/changeShip_1"}, 
					active={background="Texture/Gui/Button/changeShip_2"},},
	BlueBtn = {		normal={background="Texture/Gui/Button/btn2_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn2_2",textColor=Color.White},
					fontSize=33,
					richText=true,
					font = "font/art",
					padding={bottom=13,right=6},
					alignment=TextAnchor.MiddleCenter,},
	BlueBtn_2 = {		normal={background="Texture/Gui/Button/btn2_3",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn2_3",textColor=Color.White},},
	BlueBtn_22 = {		normal={background="Texture/Gui/Button/btn2_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn2_2",textColor=Color.White},
					fontSize=22,
					richText=true,
					padding={bottom=13},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeBtn = {		normal={background="Texture/Gui/Button/btn3_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn3_2",textColor=Color.White},
					fontSize=23,
					richText=true,
					padding={bottom=8},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeBtn_2 = {		normal={background="Texture/Gui/Button/btn3_2",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn3_2",textColor=Color.White},
					fontSize=25,
					richText=true,
					padding={bottom=8},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeBtn_3 = {		normal={background="Texture/Gui/Button/select_8",textColor=Color.LightYellow}, 
					active={background="Texture/Gui/Button/select_7",textColor=Color.LightYellow},
					fontSize=23,
					padding={bottom=6},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeBtn_4 = {		normal={background="Texture/Gui/Button/select_7",textColor=Color.LightYellow}, 
					active={background="Texture/Gui/Button/select_7",textColor=Color.LightYellow},
					fontSize=23,
					padding={bottom=6},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeBtn_30 = {		normal={background="Texture/Gui/Button/btn3_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn3_2",textColor=Color.White},
					fontSize=30,
					richText=true,
					padding={bottom=8},
					alignment=TextAnchor.MiddleCenter,},
	ShortOrangeArtBtn = {		normal={background="Texture/Gui/Button/btn3_1",textColor=Color.LightGreen2}, 
					active={background="Texture/Gui/Button/btn3_2",textColor=Color.LightGreen2},
					fontSize=30,
					richText=true,
					font = "font/art",
					padding={bottom=8},
					alignment=TextAnchor.MiddleCenter,},
	-- ServerBtn = {	normal={background="Texture/Gui/Button/server_1",textColor=Color.White}, 
					-- active={background="Texture/Gui/Button/server_2",textColor=Color.White},
					-- fontSize=35,
					-- richText=true,
					-- alignment=TextAnchor.MiddleCenter,},
	ChangeBtn = {	normal={background="Texture/Gui/Button/change_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/change_2",textColor=Color.White},
					fontSize=25,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
	TextBtn = {	normal={background="Texture/Gui/Button/text_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_2",textColor=Color.White},
					fontSize=25,
					richText=true,
					padding={top=15},
					alignment=TextAnchor.UpperCenter,},
	TextBtn_Left = {	normal={background="Texture/Gui/Button/text_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_2",textColor=Color.White},
					fontSize=25,
					richText=true,
					padding={top=20,left=105},
					alignment=TextAnchor.UpperLeft,},
	TextBtn_Center = {	normal={background="Texture/Gui/Button/text_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_2",textColor=Color.White},
					fontSize=30,
					richText=true,
					padding={top=15},
					alignment=TextAnchor.UpperCenter,},
	-- AccountBtn = {	normal={background="Texture/Gui/Button/accout_1",textColor=Color.White}, 
					-- active={background="Texture/Gui/Button/accout_2",textColor=Color.White},
					-- fontSize=35,
					-- richText=true,
					-- alignment=TextAnchor.MiddleCenter,},
	ServerBtn = {	normal={background="Texture/Gui/Button/server1_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/server1_2",textColor=Color.White},
					fontSize=30,
					richText=true,
					font = "font/art",
					padding={bottom=15,right=22},
					alignment=TextAnchor.MiddleCenter,},
	RandomBtn = {	normal={background="Texture/Gui/Button/random1_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/random1_2",textColor=Color.White},
					fontSize=23,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
	CloseBtn = {	normal={background="Texture/Gui/Button/btn4_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn4_2",textColor=Color.White},
					fontSize=23,
					richText=true,
					alignment=TextAnchor.MiddleCenter,},
	DestroyBtn = {	normal={background="Texture/Gui/Button/btn5_1"}, 
					active={background="Texture/Gui/Button/btn5_2"},},
	CloseBtn_2 = {	normal={background="Texture/Gui/Button/btn6_1"}, 
					active={background="Texture/Gui/Button/btn6_2"},},
	CloseBtn_3 = {	normal={background="Texture/Gui/Button/btn15_1"}, 
					active={background="Texture/Gui/Button/btn15_2"},},
	CloseBtn_4 = {	normal={background="Texture/Gui/Button/btn4_3"}, 
					active={background="Texture/Gui/Button/btn4_3"},},				
	ShipBtn_1 = {	normal={background="Texture/Gui/Button/btn13_2",textColor=Color.Brown}, 
					active={background="Texture/Gui/Button/btn13_1",textColor=Color.Brown},
					fontSize=23,
					alignment=TextAnchor.MiddleCenter,},
	ShipBtn_2 = {	normal={background="Texture/Gui/Button/btn13_1",textColor=Color.Brown}, 
					active={background="Texture/Gui/Button/btn13_1",textColor=Color.Brown},
					fontSize=23,
					alignment=TextAnchor.MiddleCenter,},
	SellAllBtn = {	normal={background="Texture/Gui/Button/btn7_1",textColor=Color.Brown}, 
					active={background="Texture/Gui/Button/btn7_2",textColor=Color.Brown},},
	HorizontalThumb = {	normal={background="Texture/Gui/Button/horizontalThumbBg"}, 
					active={background="Texture/Gui/Button/horizontalThumbBg"},
					padding={left=13,right=13,top=0,bottom=0},
					border={left=13,right=13,top=0,bottom=0},},
	HorizontalScrollBg = {	normal={background="Texture/Gui/Button/horizontalScrollBg"}, 
					active={background="Texture/Gui/Button/horizontalScrollBg"},
					padding={top=0,bottom=0},},
	EquipUpBtn = {	normal={background="Texture/Gui/Button/btn10_1",textColor=Color.Brown}, 
					active={background="Texture/Gui/Button/btn10_2",textColor=Color.Brown},},
	UseBtn = {	normal={background="Texture/Gui/Button/btn8_1",textColor=Color.Brown}, 
					active={background="Texture/Gui/Button/btn8_2",textColor=Color.Brown},},
	PagBtn_1 = {	normal={background="Texture/Gui/Button/btn12_1",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn12_2",textColor=Color.Yellowish},
					padding={left=0,right=0,top=0,bottom=0},
					font = "font/art",
					fontSize=30,
					alignment=TextAnchor.MiddleCenter,},
	PagBtn_2 = {	normal={background="Texture/Gui/Button/btn12_2",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn12_2",textColor=Color.Yellowish},
					padding={left=0,right=0,top=0,bottom=0},
					font = "font/art",
					fontSize=30,
					alignment=TextAnchor.MiddleCenter,},
	LeftBtn = {	normal={background="Texture/Gui/Button/btn11_1",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn11_2",textColor=Color.Yellowish},},
	RightBtn = {	normal={background="Texture/Gui/Button/btn14_1",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn14_2",textColor=Color.Yellowish},},
	LeftBtn_3 = {	normal={background="Texture/Gui/Button/btn17_1",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn17_2",textColor=Color.Yellowish},},
	RightBtn_3 = {	normal={background="Texture/Gui/Button/btn16_1",textColor=Color.Yellowish}, 
					active={background="Texture/Gui/Button/btn16_2",textColor=Color.Yellowish},},
	-- BuildBtn = {	normal={background="Texture/Gui/Button/buildBtn_1",textColor=Color.Yellowish}, 
					-- active={background="Texture/Gui/Button/buildBtn_2",textColor=Color.Yellowish},
					-- },
	TavernBtn = {	normal={background="Texture/Gui/Button/tavern_1"}, 
					active={background="Texture/Gui/Button/tavern_2"},},
	ShopBtn = {	normal={background="Texture/Gui/Button/shop_1"}, 
					active={background="Texture/Gui/Button/shop_2"},},
	MainBtn = {	normal={background="Texture/Gui/Button/main_1"}, 
					active={background="Texture/Gui/Button/main_2"},},
	LabBtn = {	normal={background="Texture/Gui/Button/lab_1"}, 
					active={background="Texture/Gui/Button/lab_2"},},
	ShipyardBtn = {	normal={background="Texture/Gui/Button/shipyard_1"}, 
					active={background="Texture/Gui/Button/shipyard_2"},},
	HeroBtn = {	normal={background="Texture/Gui/Button/hero_1"}, 
					active={background="Texture/Gui/Button/hero_2"},},
	GiveUpBtn = {	normal={background="Texture/Gui/Button/giveup_1"}, 
					active={background="Texture/Gui/Button/giveup_2"},},
	ViewBtn = {	normal={background="Texture/Gui/Button/view"}, 
					active={background="Texture/Gui/Button/view"},},
	EquipBtn = {	normal={background="Texture/Gui/Button/equip_1"}, 
					active={background="Texture/Gui/Button/equip_2"},},
	ItemBtn = {	normal={background="Texture/Gui/Button/item_1"}, 
					active={background="Texture/Gui/Button/item_2"},},
	SkillBtn = {	normal={background="Texture/Gui/Button/skill_1"}, 
					active={background="Texture/Gui/Button/skill_2"},},
	ShipsBtn = {	normal={background="Texture/Gui/Button/ships_1"}, 
					active={background="Texture/Gui/Button/ships_2"},},
	FamilyBtn = {	normal={background="Texture/Gui/Button/family_1"}, 
					active={background="Texture/Gui/Button/family_2"},},
	FriendBtn = {	normal={background="Texture/Gui/Button/friend_1"}, 
					active={background="Texture/Gui/Button/friend_2"},},
	Friend2Btn = {	normal={background="Texture/Gui/Button/friend_3"}, 
					active={background="Texture/Gui/Button/friend_4"},},
	LogbookBtn = {	normal={background="Texture/Gui/Button/logbook_1"}, 
					active={background="Texture/Gui/Button/logbook_2"},},
	LevelHarborBtn = {	normal={background="Texture/Gui/Button/levelHarborBtn_1"}, 
					active={background="Texture/Gui/Button/levelHarborBtn_2"},},
	MenuBtn_1 = {	normal={background="Texture/Gui/Button/menuBtn_1"}, 
					active={background="Texture/Gui/Button/menuBtn_2"},},
	MenuBtn_2 = {	normal={background="Texture/Gui/Button/menuBtn_2"}, 
					active={background="Texture/Gui/Button/menuBtn_1"},},
	ChatBtn = {	normal={background="Texture/Gui/Button/chatBtn_1"}, 
					active={background="Texture/Gui/Button/chatBtn_1"},},
	-- ToolBtn = {	normal={background="Texture/Gui/Button/toolBtn_1"}, 
					-- active={background="Texture/Gui/Button/toolBtn_2"},},
	SettingBtn = {	normal={background="Texture/Gui/Button/setting_1"}, 
					active={background="Texture/Gui/Button/setting_2"},},
	RechargeBtn = {	normal={background="Texture/Gui/Button/recharge_1"}, 
					active={background="Texture/Gui/Button/recharge_1"},},		
	MapBtn = {	normal={background="Texture/Gui/Button/map_1"}, 
					active={background="Texture/Gui/Button/map_2"},},
	YesBtn = {	normal={background="Texture/Gui/Button/yesBtn_1"}, 
					active={background="Texture/Gui/Button/yesBtn_2"},},
	NoBtn = {	normal={background="Texture/Gui/Button/noBtn_1"}, 
					active={background="Texture/Gui/Button/noBtn_2"},},
	-- FightSlotBtn_1 = {	normal={background="Texture/Gui/BG/bg17_1"}, 
					-- active={background="Texture/Gui/BG/bg17_2"},},
	-- FightSlotBtn_2 = {	normal={background="Texture/Gui/BG/bg17_2"}, 
					-- active={background="Texture/Gui/BG/bg17_2"},},
	-- SlotBtn_1 = {	normal={background="Texture/Gui/BG/bg10_1"}, 
					-- active={background="Texture/Gui/BG/bg10_2"},},
	-- SlotBtn_2 = {	normal={background="Texture/Gui/BG/bg10_2"}, 
					-- active={background="Texture/Gui/BG/bg10_2"},},
	EditBtn = {	normal={background="Texture/Gui/Button/editBtn_1"}, 
					active={background="Texture/Gui/Button/editBtn_2"},},	
	AddFriendBtn = {	normal={background="Texture/Gui/Button/addFriend_1"}, 
					active={background="Texture/Gui/Button/addFriend_2"},},	
	AudioBtn_1 = {	normal={background="Texture/Gui/Button/audioBtn_1"}, 
					active={background="Texture/Gui/Button/audioBtn_2"},},	
	AudioBtn_2 = {	normal={background="Texture/Gui/Button/audioBtn_2"}, 
					active={background="Texture/Gui/Button/audioBtn_1"},},	
	LeftBtn_1 = {	normal={background="Texture/Gui/Button/left_1"}, 
					active={background="Texture/Gui/Button/left_2"},},	
	LeftBtn_2 = {	normal={background="Texture/Gui/Button/left_3"}, 
					active={background="Texture/Gui/Button/left_3"},},	
	RightBtn_1 = {	normal={background="Texture/Gui/Button/right_1"}, 
					active={background="Texture/Gui/Button/right_2"},},	
	RightBtn_2 = {	normal={background="Texture/Gui/Button/right_3"}, 
					active={background="Texture/Gui/Button/right_3"},},	
	FriendAddBtn = {	normal={background="Texture/Gui/Button/friendAdd_1"}, 
					active={background="Texture/Gui/Button/friendAdd_2"},},	
	FriendDelBtn = {	normal={background="Texture/Gui/Button/friendDel_1"}, 
					active={background="Texture/Gui/Button/friendDel_2"},},	
	FriendChatBtn = {	normal={background="Texture/Gui/Button/friendChat_1"}, 
					active={background="Texture/Gui/Button/friendChat_2"},},	
	FriendFindBtn = {	normal={background="Texture/Gui/Button/friendFind_1"}, 
					active={background="Texture/Gui/Button/friendFind_2"},},	
	CancelBtn = {	normal={background="Texture/Gui/Button/cancel_1"}, 
					active={background="Texture/Gui/Button/cancel_2"},},	
	ChannelBtn_0 = {	normal={textColor=Color.ChannelColor1}, 
					active={textColor=Color.ChannelColor1},
					fontSize=35,
					richText=true,
					alignment=TextAnchor.MiddleCenter,
					font = "font/art",},	
	SmallBlueBtn_1 = {	normal={background="Texture/Gui/Button/btn20_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn20_2",textColor=Color.White},
					fontSize=35,
					alignment=TextAnchor.MiddleCenter,},	
					
	SelectMoneyBtn_1 = {	normal={background="Texture/Gui/Button/btn20_1",textColor=Color.SelectMoney1}, 
					active={background="Texture/Gui/Button/btn20_2",textColor=Color.LightGreen},
					fontSize=25,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},	
	AutoEquipBtn = {	normal={background="Texture/Gui/Button/btn20_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/btn20_2",textColor=Color.LightGreen},
					fontSize=25,
					padding={right=9},
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},	
	SelectMoneyBtn_2 = {	normal={background="Texture/Gui/Button/btn20_2",textColor=Color.LightGreen}, 
					active={background="Texture/Gui/Button/btn20_2",textColor=Color.LightGreen},
					fontSize=25,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},	
	-- SmallBlueBtn_2 = {	normal={background="Texture/Gui/Button/btn21_1",textColor=Color.White}, 
					-- active={background="Texture/Gui/Button/btn21_2",textColor=Color.White},
					-- fontSize=35,
					-- alignment=TextAnchor.MiddleCenter,},	
	ChannelBtn_1 = {	normal={textColor=Color.ChannelColor2}, 
				active={textColor=Color.ChannelColor2},
				fontSize=35,
				richText=true,
				alignment=TextAnchor.MiddleCenter,
				font = "font/art",},	
	ChannelBtn_3 = {	normal={textColor=Color.ChannelColor3}, 
				active={textColor=Color.ChannelColor3},
				fontSize=35,
				richText=true,
				alignment=TextAnchor.MiddleCenter,
				font = "font/art",},	
	AddBtn = {	normal={background="Texture/Gui/Button/add_1"}, 
				active={background="Texture/Gui/Button/add_2"},},	
	CopyMapBtn = {	normal={background="Texture/Gui/Button/copyMap_1"}, 
				active={background="Texture/Gui/Button/copyMap_2"},},	
	CleanBtn = {	normal={background="Texture/Gui/Button/clean_1"}, 
				active={background="Texture/Gui/Button/clean_2"},},	
	FightBtn = {	normal={background="Texture/Gui/Button/fight_1"}, 
				active={background="Texture/Gui/Button/fight_2"},},	
	GetBtn_3 = {	normal={background="Texture/Gui/Button/get_3"}, 
				active={background="Texture/Gui/Button/get_3"},},	
	SpeedUpBtn = {	normal={background="Texture/Gui/Button/speedUp_1"}, 
				active={background="Texture/Gui/Button/speedUp_2"},},	
	NotGuideBtn = {	normal={background="Texture/Gui/Button/notGuide"}, 
				active={background="Texture/Gui/Button/notGuide"},},	
	SelectBtn_1 = {	normal={background="Texture/Gui/Button/select_1"}, 
				active={background="Texture/Gui/Button/select_2"},},	
	SelectBtn_2 = {	normal={background="Texture/Gui/Button/select_2"}, 
				active={background="Texture/Gui/Button/select_1"},},	
	SetBtn = {	normal={background="Texture/Gui/Button/set_1"}, 
				active={background="Texture/Gui/Button/set_2"},},	
	TaskBtn = {	normal={background="Texture/Gui/Button/task_1"}, 
				active={background="Texture/Gui/Button/task_2"},},	
	MoveBtn = {	normal={background="Texture/Gui/Button/moveBtn_1"}, 
				active={background="Texture/Gui/Button/moveBtn_1"},},	
	MoveBtn_2 = {	normal={background="Texture/Gui/Button/move_1"}, 
				active={background="Texture/Gui/Button/move_2"},},	
	MoveBtn_3 = {	normal={background="Texture/Gui/Button/move"}, 
					active={background="Texture/Gui/Button/move"},},
	FlyBtn = {	normal={background="Texture/Gui/Button/flyBtn_1"}, 
				active={background="Texture/Gui/Button/flyBtn_1"},},	
	FlyBtn_2 = {normal={background="Texture/Gui/Button/fly"}, 
				active={background="Texture/Gui/Button/fly"},},	
	GetBtn = {	normal={background="Texture/Gui/Button/get_1"}, 
				active={background="Texture/Gui/Button/get_2"},},	
	RefreshBtn = {	normal={background="Texture/Gui/Button/refresh_1"}, 
				active={background="Texture/Gui/Button/refresh_2"},},	
	CompleteBtn = {	normal={background="Texture/Gui/Button/complete_1"}, 
				active={background="Texture/Gui/Button/complete_2"},},
	GiveBtn = {	normal={background="Texture/Gui/Button/give_1"}, 
				active={background="Texture/Gui/Button/give_2"},},
	StartBtn = {	normal={background="Texture/Gui/Button/start_1"}, 
				active={background="Texture/Gui/Button/start_2"},},
	SelectBtn = {	normal={background="Texture/Gui/Button/select_3"}, 
				active={background="Texture/Gui/Button/select_4"},},
	ChannelSelectBtn_1 = {	normal={background="Texture/Gui/Button/channel_1",textColor=Color.ChannelSelectColor}, 
				active={background="Texture/Gui/Button/channel_1",textColor=Color.ChannelSelectColor},
				fontSize=25,
				alignment=TextAnchor.MiddleCenter,},
	ChannelSelectBtn_2 = {	normal={background="Texture/Gui/Button/channel_2",textColor=Color.ChannelSelectColor}, 
				active={background="Texture/Gui/Button/channel_1",textColor=Color.ChannelSelectColor},
				fontSize=25,
				alignment=TextAnchor.MiddleCenter,},
	EnterBtn = {	normal={background="Texture/Gui/Button/enter_1",textColor=Color.ChannelSelectColor}, 
				active={background="Texture/Gui/Button/enter_2",textColor=Color.ChannelSelectColor},},
	SelectServerBtn = {	normal={background="Texture/Gui/Button/selectServer_1",textColor=Color.White}, 
				active={background="Texture/Gui/Button/selectServer_2",textColor=Color.White},
				fontSize=35,
				font = "font/art",
				padding={top=30,left=100},
				alignment=TextAnchor.MiddleLeft,},
	SelectBtn_3 = {	normal={background="Texture/Gui/Button/select_5"}, 
				active={background="Texture/Gui/Button/select_6"},},
	SelectBtn_4 = {	normal={background="Texture/Gui/Button/select_6"}, 
				active={background="Texture/Gui/Button/select_6"},},
	SelectBtn_5 = {	normal={background="Texture/Gui/Button/select_8",textColor=Color.White}, 
				active={background="Texture/Gui/Button/select_7",textColor=Color.White},
				fontSize=25,
				padding={bottom=5},
				alignment=TextAnchor.MiddleCenter,},
	SelectBtn_6 = {	normal={background="Texture/Gui/Button/select_7",textColor=Color.White}, 
				active={background="Texture/Gui/Button/select_7",textColor=Color.White},
				fontSize=25,
				padding={bottom=5},
				alignment=TextAnchor.MiddleCenter,},
	SelectBtn_7 = {	normal={textColor=Color.White}, 
					active={background="Texture/Gui/Bg/bg50_2",textColor=Color.White},
					fontSize=25,
					richText=true,
					font = "font/art",
					alignment=TextAnchor.MiddleCenter,},
	-- ChangeSailorBtn = {	normal={background="Texture/Gui/Button/changeSailor_1"}, 
					-- active={background="Texture/Gui/Button/changeSailor_2"},},
	DrinkingBtn = {	normal={background="Texture/Gui/Button/drinking_1"}, 
					active={background="Texture/Gui/Button/drinking_2"},},
	DrinkingBtn_2 = {	normal={background="Texture/Gui/Button/drinking_3"}, 
					active={background="Texture/Gui/Button/drinking_3"},},
	MapBtn_1 = {	normal={background="Texture/Gui/Button/sea_1"}, 
					active={background="Texture/Gui/Button/sea_2"},},
	MapBtn_2 = {	normal={background="Texture/Gui/Button/sea_2"}, 
					active={background="Texture/Gui/Button/sea_2"},},
	MapBtn_3 = {	normal={background="Texture/Gui/Button/sea_3"}, 
					active={background="Texture/Gui/Button/sea_4"},},
	MapBtn_4 = {	normal={background="Texture/Gui/Button/sea_4"}, 
					active={background="Texture/Gui/Button/sea_4"},},
	SignupBtn = {	normal={background="Texture/Gui/Button/signup_1"}, 
					active={background="Texture/Gui/Button/signup_2"},},				
	ActivityBtn = {normal={background="Texture/Gui/Button/activity_1"}, 
					active={background="Texture/Gui/Button/activity_2"},},
	FirstChargeBtn = {normal={background="Texture/Gui/Button/firstCharge"}, 
					active={background="Texture/Gui/Button/firstCharge"},},
	ActivityBtn_2 = {normal={background="Texture/Gui/Button/FirstRechange_2"}, 
					active={background="Texture/Gui/Button/FirstRechange_2"},},
	ActivityBtn_3 = {normal={background="Texture/Gui/Button/LevelAward_1"}, 
					active={background="Texture/Gui/Button/LevelAward_2"},},
	ActivityBtn_4 = {normal={background="Texture/Gui/Button/LevelAward_2"}, 
					active={background="Texture/Gui/Button/LevelAward_2"},},
	ActivityBtn_5 = {normal={background="Texture/Gui/Button/RechangeAward_1"}, 
					active={background="Texture/Gui/Button/RechangeAward_2"},},
	ActivityBtn_6 = {normal={background="Texture/Gui/Button/RechangeAward_2"}, 
					active={background="Texture/Gui/Button/RechangeAward_2"},},
	ActivityBtn_7 = {normal={background="Texture/Gui/Button/GoodDrinking_1"}, 
					active={background="Texture/Gui/Button/GoodDrinking_2"},},
	ActivityBtn_8 = {normal={background="Texture/Gui/Button/GoodDrinking_2"}, 
					active={background="Texture/Gui/Button/GoodDrinking_2"},},
	ActivityBtn_9 = {normal={background="Texture/Gui/Button/HarborBattle_1"}, 
					active={background="Texture/Gui/Button/HarborBattle_2"},},
	ActivityBtn_10 = {normal={background="Texture/Gui/Button/HarborBattle_2"}, 
					active={background="Texture/Gui/Button/HarborBattle_2"},},
	ActivityBtn_11 = {normal={background="Texture/Gui/Button/enemyTreasure_1"}, 
					active={background="Texture/Gui/Button/enemyTreasure_2"},},
	ActivityBtn_12 = {normal={background="Texture/Gui/Button/enemyTreasure_2"}, 
					active={background="Texture/Gui/Button/enemyTreasure_2"},},
	ActivityBtn_13 = {normal={background="Texture/Gui/Button/emenyAttack_1"}, 
					active={background="Texture/Gui/Button/emenyAttack_2"},},
	ActivityBtn_14 = {normal={background="Texture/Gui/Button/emenyAttack_2"}, 
					active={background="Texture/Gui/Button/emenyAttack_2"},},
	ActivityBtn_15= {normal={background="Texture/Gui/Button/collectTreasureMap_1"}, 
					active={background="Texture/Gui/Button/collectTreasureMap_2"},},
	ActivityBtn_16 = {normal={background="Texture/Gui/Button/collectTreasureMap_2"}, 
					active={background="Texture/Gui/Button/collectTreasureMap_2"},},
	ActivityBtn_17 = {normal={background="Texture/Gui/Button/gift_1"}, 
					active={background="Texture/Gui/Button/gift_2"},},
	ActivityBtn_18 = {normal={background="Texture/Gui/Button/gift_2"}, 
					active={background="Texture/Gui/Button/gift_2"},},
	ActivityBtn_19 = {normal={background="Texture/Gui/Button/rmbShop_1"}, 
					active={background="Texture/Gui/Button/rmbShop_2"},
					},
	ActivityBtn_20 = {normal={background="Texture/Gui/Button/rmbShop_2"}, 
					active={background="Texture/Gui/Button/rmbShop_2"},
					},
	ActivityBtn_21 = {normal={background="Texture/Gui/Button/deadGame_1"}, 
					active={background="Texture/Gui/Button/deadGame_2"},
					},
	ActivityBtn_22 = {normal={background="Texture/Gui/Button/deadGame_2"}, 
					active={background="Texture/Gui/Button/deadGame_2"},
					},
	ActivityBtn_23 = {normal={background="Texture/Gui/Button/costAward_1"}, 
					active={background="Texture/Gui/Button/costAward_2"},
					},
	ActivityBtn_24 = {normal={background="Texture/Gui/Button/costAward_2"}, 
					active={background="Texture/Gui/Button/costAward_2"},
					},
	ActivityBtn_25 = {normal={background="Texture/Gui/Button/fish_1"}, 
					active={background="Texture/Gui/Button/fish_2"},
					},
	ActivityBtn_26 = {normal={background="Texture/Gui/Button/fish_2"}, 
					active={background="Texture/Gui/Button/fish_2"},
					},
	ActivityBtn_27 = {normal={background="Texture/Gui/Button/goods_1"}, 
					active={background="Texture/Gui/Button/goods_2"},
					},
	ActivityBtn_28 = {normal={background="Texture/Gui/Button/goods_2"}, 
					active={background="Texture/Gui/Button/goods_2"},
					},
	ActivityBtn_29 = {normal={background="Texture/Gui/Button/gamble_1"}, 
					active={background="Texture/Gui/Button/gamble_2"},
					},
	ActivityBtn_30 = {normal={background="Texture/Gui/Button/gamble_2"}, 
					active={background="Texture/Gui/Button/gamble_2"},
					},
    -- 活动的月卡
	ActivityBtn_card_1 = {normal={background="Texture/Gui/Button/monthCard_1"}, 
					active={background="Texture/Gui/Button/monthCard_2"},
					},
	ActivityBtn_card_2 = {normal={background="Texture/Gui/Button/monthCard_2"}, 
					active={background="Texture/Gui/Button/monthCard_2"},
					},
	--月卡购买和领取按钮
	ActivityBtn_card_buy = {normal={background="Texture/Gui/Button/card_buy_1"}, 
					active={background="Texture/Gui/Button/card_buy_2"},
					},
	ActivityBtn_card_get = {normal={background="Texture/Gui/Button/card_get_1"}, 
					active={background="Texture/Gui/Button/card_get_2"},
					},			
	Exchange = {normal={background="Texture/Gui/Button/exchange_1"}, 
					active={background="Texture/Gui/Button/exchange_2"},},
	Delect = {normal={background="Texture/Gui/Button/delete_1"}, 
					active={background="Texture/Gui/Button/delete_2"},},
	EmenyAttack = {normal={background="Texture/Gui/Button/emenyAttack_1"}, 
					active={background="Texture/Gui/Button/emenyAttack_1"},},
	EnemyTreasure = {normal={background="Texture/Gui/Button/enemyTreasure_1"}, 
					active={background="Texture/Gui/Button/enemyTreasure_1"},},
	CollectTreasureMap = {normal={background="Texture/Gui/Button/collectTreasureMap_1"}, 
					active={background="Texture/Gui/Button/collectTreasureMap_1"},},
	DailyPanel_Award_1 = {
		normal = {
			background = "Texture/Icon/Item/45"
		},
	},
	DailyPanel_Award_2 = {
		normal = {
			background = "Texture/Icon/Item/46"
		}
	},
	DailyPanel_Award_3 = {
		normal = {
			background = "Texture/Icon/Item/47"
		},
	},
	DailyPanel_Award_4 = {
		normal = {
			background = "Texture/Icon/Item/48"
		},
	},
	DailyPanel_Award_5 = {
		normal = {
			background = "Texture/Icon/Item/49"
		},
	},
	--立即充值
	RechangeEntry = {normal={background="Texture/Gui/Button/RechangeEntry_1"}, 
					active={background="Texture/Gui/Button/RechangeEntry_2"},},
	--特权界面的对错号图标
	Vip_Warranty_true = {normal = {background = "Texture/Gui/Bg/Vip_Warranty_true"},},
	Vip_Warranty_false= {normal = {background = "Texture/Gui/Bg/Vip_Warranty_false"},},
	--前往宝箱
	SeekTreasure_goto= {normal = {background = "Texture/Gui/Button/SeekTreasure_btn1"},},
}

GUIStyleLabel = {
	Center_20_Yellow4 = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Yellow4}},
	Left_20_White_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.White}},
	Center_26_Power_Yellow = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					wordWrap=true,
					-- font = "font/art",
					fontStyle = FontStyle.BoldAndItalic,
					normal={textColor=Color.Yellow3}},
	Left_20_White = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.White}},
	Left_15_White = { alignment=TextAnchor.UpperLeft,
					fontSize=15,
					richText=true,
					normal={textColor=Color.White}},
	Left_22_White = { alignment=TextAnchor.UpperLeft,
					fontSize=22,
					richText=true,
					normal={textColor=Color.White}},
	Left_20_White_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_20_Orange = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Orange}},
	Center_20_Black = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Black}},
	Center_20_Lime = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Lime}},
	Center_20_LightBlue = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.LightBlue}},
	Left_20_Black = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Black}},
	Left_20_Brown = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Brown}},
	Left_18_Lime = { alignment=TextAnchor.UpperLeft,
					fontSize=18,
					richText=true,
					normal={textColor=Color.Lime}},
	Right_18_Lime = { alignment=TextAnchor.UpperRight,
					fontSize=18,
					richText=true,
					normal={textColor=Color.Lime}},
	Right_20_Lime = { alignment=TextAnchor.UpperRight,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Lime}},
	Left_20_Lime = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Lime}},
	Center_20_Cyan = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Cyan}},
	Right_20_White = { alignment=TextAnchor.UpperRight,
					fontSize=20,
					richText=true,
					normal={textColor=Color.White}},
	Left_20_Gray = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Gray}},
	-- Gray_20_Lime = { alignment=TextAnchor.UpperLeft,
					-- fontSize=20,
					-- richText=true,
					-- normal={textColor=Color.Gray}},
	Center_26_White = { alignment=TextAnchor.UpperCenter,
					fontSize=26,
					richText=true,
					normal={textColor=Color.White}},
	Center_20_White = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.White}},
	MCenter_19_White = { alignment=TextAnchor.MiddleCenter,
					fontSize=19,
					richText=true,
					normal={textColor=Color.White}},
	
	Center_20_Yellowish = {alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Yellowish}},
	Center_19_White = { alignment=TextAnchor.UpperCenter,
					fontSize=19,
					richText=true,
					normal={textColor=Color.White}},
	Center_12_White = { alignment=TextAnchor.UpperCenter,
					fontSize=16,
					richText=true,
					normal={textColor=Color.White}},
	Center_18_White = { alignment=TextAnchor.UpperCenter,
					fontSize=18,
					richText=true,
					normal={textColor=Color.White}},
	Center_20_Redbean= { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Redbean}},
	Center_20_Red = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Red}},
	Center_15_Red = { alignment=TextAnchor.UpperRight,
					fontSize=15,
					richText=true,
					normal={textColor=Color.Red}},
	Left_20_Red = { alignment=TextAnchor.UpperLeft	,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Red}},
	Center_20_White_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_20_White_LineSpacing10 = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					fixedHeight=10,
					normal={textColor=Color.White}},
	Center_25_Brown_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Left_23_Brown_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=23,
					wordWrap=true,
					normal={textColor=Color.Brown}},
	Center_25_SimpleYellow = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.SimpleYellow}},
	Center_DailyTitle_SimpleYellow = { alignment=TextAnchor.MiddleCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.SimpleYellow}},
	Center_22_White = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	Center_22_White_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=22,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	LCenter_22_Red = { alignment=TextAnchor.LowerCenter,
				fontSize=22,
				richText=true,
				normal={textColor=Color.Red}},
	Left_23_Brown_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=23,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Brown}},
	Left_25_LightYellow_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=23,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.LightYellow}},
	
	Left_45_Yellow_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=45,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	Left_30_LightYellow_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=28,
					wordWrap=true,
					font = "font/art",
					normal={textColor=Color.LightYellow}},
	Center_25_LightYellow = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.LightYellow}},
	LCenter_22_White = { alignment=TextAnchor.LowerCenter,
					fontSize=22,
					richText=true,
					normal={textColor=Color.White}},
	Left_20_Black_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Black}},
	MLeft_20_Black_WordWrap = { alignment=TextAnchor.MiddleLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Black}},
	LLeft_20_Black_WordWrap = { alignment=TextAnchor.LowerLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Black}},
	MCenter_20_Orange = { alignment=TextAnchor.MiddleCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Orange}},
	MCenter_20_Orange_Unscale = { alignment=TextAnchor.MiddleCenter,
					fontSize=20,
					richText=true,
					unscale = true,
					normal={textColor=Color.Orange}},
	Right_20_DeepBlue = { alignment=TextAnchor.UpperRight,
					fontSize=20,
					richText=true,
					normal={textColor=Color.DeepBlue}},
	Center_22_LightGreen_Art = {	alignment=TextAnchor.UpperCenter,
				fontSize=22,
				richText=true,
				font = "font/art",
				normal={textColor=Color.LightGreen}},
	Right_25_Yellow = { alignment=TextAnchor.UpperRight,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Yellow}},
	Left_25_LightBrown_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.LightBrown}},
	Left_25_White_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.White}},
	Left_25_Purple_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					font = "font/art",
					normal={textColor=Color.Purple}},
	Left_25_White_Art_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_25_Yellow_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Yellow}},
	Left_25_Brown_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Brown}},
	Left_25_Brown = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Brown}},
	Left_23_White = { alignment=TextAnchor.UpperLeft,
					fontSize=23,
					richText=true,
					normal={textColor=Color.White}},
	Left_25_Lime = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Lime}},
	Left_25_Black_Art_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					font = "font/art",
					normal={textColor=Color.Black}},
	Left_25_DeepBlue_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					font = "font/art",
					normal={textColor=Color.DeepBlue}},
	Center_25_DeepBlue_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.DeepBlue}},
	MCenter_25_White_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					font = "font/art",
					richText=true,
					normal={textColor=Color.White}},
	Left_25_Black = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Black}},
	Right_25_LightBlue = { alignment=TextAnchor.UpperRight,
					fontSize=25,
					richText=true,
					normal={textColor=Color.LightBlue}},
	Left_25_LightBlue = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.LightBlue}},
	Left_25_LightBrown = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.LightBrown}},
	Left_25_LightGreen_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightGreen}},
	Left_25_White = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	Left_25_White_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_25_Lime_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_25_Red_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					font = "font/art",
					normal={textColor=Color.Red}},
	Left_25_Yellowish = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Yellowish}},
	Left_25_Gray = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Gray}},
	Right_25_White = { alignment=TextAnchor.UpperRight,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	Center_25_White = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	Center_23_White = { alignment=TextAnchor.UpperCenter,
					fontSize=23,
					richText=true,
					normal={textColor=Color.White}},
	Center_24_Custom_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	MCenter_21_White = { alignment=TextAnchor.MiddleCenter,
					fontSize=21,
					richText=true,
					normal={textColor=Color.White}},
	MCenter_25_Gray = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Gray}},
	MCenter_25_Orange = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Orange}},
	MCenter_30_Orange_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Orange}},
	MCenter_25_Gray2 = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Gray2}},
	MCenter_30_Gray2_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					font = "font/art",
					richText=true,
					normal={textColor=Color.Gray2}},
	MCenter_25_White = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	MCenter_25_SimpleYellow = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.SimpleYellow}},
	MCenter_25_SimpleYellow2 = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.SimpleYellow2}},
	MCenter_25_SimpleYellow2_Unscale = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					unscale = true,
					normal={textColor=Color.SimpleYellow2}},
	MCenter_20_Lime_Unscale = { alignment=TextAnchor.MiddleCenter,
					fontSize=20,
					richText=true,
					unscale = true,
					normal={textColor=Color.Lime}},
	LCenter_25_White = { alignment=TextAnchor.LowerCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.White}},
	LCenter_25_Red = { alignment=TextAnchor.LowerCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Red}},
	Left_25_Redbean_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	LLeft_25_Change_Art = { alignment=TextAnchor.LowerLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_25_Redbean = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Redbean}},
	Left_22_Redbean = { alignment=TextAnchor.UpperLeft,
					fontSize=22,
					richText=true,
					normal={textColor=Color.Redbean}},
	Center_22_Lime_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=22,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_25_Redbean_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Redbean}},
	Center_25_Black = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Black}},
	Center_25_Red = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Red}},
	Center_25_Red_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Red}},
	Center_25_Redbean_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Center_25_Redbean = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Redbean}},
	Center_25_Green = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Green}},
	Left_25_Black_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Black}},
	MLeft_25_Black_WordWrap = { alignment=TextAnchor.MiddleLeft,
					fontSize=25,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.Black}},
	Center_25_White_Art = {font = "font/art",
					fontSize=25,
					alignment=TextAnchor.UpperCenter,
					normal={textColor=Color.White}},
	Center_25_Gray_Art = {font = "font/art",
					fontSize=25,
					alignment=TextAnchor.UpperCenter,
					normal={textColor=Color.Gray}},
	Center_20_White_WordWrap = {fontSize=20,
					wordWrap=true,
					alignment=TextAnchor.UpperCenter,
					normal={textColor=Color.White}},
	MLeft_18_White_WordWrap = {fontSize=18,
					wordWrap=true,
					alignment=TextAnchor.MiddleLeft,
					normal={textColor=Color.White}},
	Right_18_White = {fontSize=20,
					alignment=TextAnchor.UpperRight,
					normal={textColor=Color.White}},
	Left_25_Brown_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Center_20_Gray_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					font = "font/art",
					normal={textColor=Color.Gray}},
	Center_20_Lime_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=20,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Center_25_Lime_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Center_30_Lime_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_30_Lime_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	MCenter_25_Lime = { alignment=TextAnchor.MiddleCenter,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Lime}},
	MCenter_20_Lime = { alignment=TextAnchor.MiddleCenter,
					fontSize=20,
					richText=true,
					normal={textColor=Color.Lime}},
	MCenter_30_Lime_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_25_Brown2 = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					normal={textColor=Color.Brown2}},
	Left_20_Orange_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=23,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Orange}},
	Center_25_Orange = {font = "font/art",
					fontSize=25,
					alignment=TextAnchor.UpperCenter,
					normal={textColor=Color.Orange}},
	
	Left_30_Lime = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Lime}},
	Left_30_Brown_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Left_31_Custom_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	MLeft_30_White = { alignment=TextAnchor.MiddleLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	MCenter_30_White = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	Center_30_Change = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	
	Right_30_White = { alignment=TextAnchor.UpperRight,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	Left_30_White = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	Left_30_White_Unscale = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					unscale=true,
					normal={textColor=Color.White}},
	
	LLeft_30_Change_Art = { alignment=TextAnchor.LowerLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_30_DeepBlue_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.DeepBlue}},
	Left_30_Black = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Black}},
	Left_30_Black_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					font = "font/art",
					normal={textColor=Color.Black}},
	Center_30_LightBlue_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightBlue}},
	Center_30_LightYellow_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightYellow}},
	MCenter_30_White_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					font = "font/art",
					richText=true,
					normal={textColor=Color.White}},
	Center_30_LightYellow_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightYellow}},
	Center_30_Yellow = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	Left_30_Yellow = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	MLeft_30_Yellow = { alignment=TextAnchor.MiddleLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	MRight_30_Yellow = { alignment=TextAnchor.MiddleRight,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	LLeft_30_Yellow = { alignment=TextAnchor.LowerLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	LCenter_30_Yellow = { alignment=TextAnchor.LowerCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow}},
	Center_30_White = {	alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.White}},
	Center_30_White_clipping45 = {	alignment=TextAnchor.UpperCenter,
				fontSize=30,
				clipping=45,
				richText=true,
				normal={textColor=Color.White}},
	
	Center_30_Orange = {alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Orange}},
	Left_30_Orange = {alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Orange}},
	Center_30_Green = {alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Green}},
	Center_30_White_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	LevelUp_30 = {alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LevelUp}},
	PowerChange_1 = {alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LevelUp}},
	PowerChange_2 = {alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.PowerChange}},
	PowerChange_3 = {alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_30_White_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Right_30_White_Art = { alignment=TextAnchor.UpperRight,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	MCenter_30_Redbean_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Center_30_Redbean = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Redbean}},
	Center_30_Black = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Black}},
	Center_30_Gray = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Gray}},
	Left_30_Brown = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Brown}},
	Left_30_Yellowish = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Yellowish}},
	Center_30_Brown = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					normal={textColor=Color.Brown}},
	Center_30_Brown_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Left_30_Redbean_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Left_30_LightGreen_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightGreen}},
	Left_25_LightGreen_Art_WordWrap = { alignment=TextAnchor.UpperLeft,
					fontSize=25,
					richText=true,
					font = "font/art",
					wordWrap=true,
					normal={textColor=Color.LightGreen}},
	Left_30_Redbean = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Redbean}},
	
	Left_30_Gray = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Gray}},
	Left_30_Gray_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Gray}},
	Left_30_Green2 = { alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					normal={textColor=Color.Green2}},
	Center_35_Black_Art = {	alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Black}},
	Center_35_LightGreen_Art = {	alignment=TextAnchor.UpperCenter,
				fontSize=35,
				richText=true,
				font = "font/art",
				normal={textColor=Color.LightGreen}},
	Center_35_Black = {	alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Black}},
	Center_35_White = {	alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					normal={textColor=Color.White}},
	Center_35_White_Art = {	alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Center_35_Red = {	alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Red}},
	Left_35_Black = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Black}},
	Left_35_White = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.White}},
	Left_35_White_Art = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	Left_35_Gray = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Gray}},
	Left_35_Green = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Green}},
	Left_35_Red = {alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Red}},
	Left_35_Redbean = { alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Redbean}},
	Left_35_Redbean_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Left_35_Brown_Art = { alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Left_35_Brown = { alignment=TextAnchor.UpperLeft,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Brown}},
	Left_35_Earth = { alignment=TextAnchor.UpperLeft,
					fontSize=35,
					normal={textColor=Color.Earth}},
	MCenter_35_Redbean_Art = { alignment=TextAnchor.MiddleCenter,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Center_40_Orange = { alignment=TextAnchor.UpperCenter,
					fontSize=40,
					normal={textColor=Color.Orange}},
	Center_40_Naturals = { alignment=TextAnchor.UpperCenter,
					fontSize=40,
					normal={textColor=Color.Naturals}},
	Center_35_Redbean_Art = { alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Center_35_Redbean = { alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Redbean}},
	Center_35_Yellow = { alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					normal={textColor=Color.Yellow}},
	Center_35_Brown_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=35,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Center_40_White_Bold = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					richText=true,
					fontStyle=FontStyle.Bold,
					normal={textColor=Color.White}},
	Center_40_Black_Bold = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					richText=true,
					fontStyle=FontStyle.Bold,
					normal={textColor=Color.Black}},
	Center_40_Lime_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					font = "font/art",
					normal={textColor=Color.Lime}},
	Left_40_Gray = {alignment=TextAnchor.UpperLeft,
					fontSize=40,
					richText=true,
					normal={textColor=Color.Gray}},
	MCenter_40_Gray = {alignment=TextAnchor.MiddleCenter,
					fontSize=40,
					richText=true,
					normal={textColor=Color.Gray}},
	MCenter_40_White = {alignment=TextAnchor.MiddleCenter,
					fontSize=40,
					richText=true,
					normal={textColor=Color.White}},
	Left_40_Green = {alignment=TextAnchor.UpperLeft,
					fontSize=40,
					richText=true,
					normal={textColor=Color.Green}},
	Left_40_Yellowish_Art = {alignment=TextAnchor.UpperLeft,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellowish}},
	Left_30_Yellowish_Art = {alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellowish}},
	Center_40_Yellowish_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellowish}},
	Center_40_Redbean_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	MCenter_40_White_Art = {alignment=TextAnchor.MiddleCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.White}},
	MCenter_40_Gray_Art = {alignment=TextAnchor.MiddleCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Gray}},
	Left_40_White_WordWrap = {alignment=TextAnchor.UpperLeft,
					fontSize=40,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.White}},
	
	Center_40_Brown_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=40,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Center_45_Brown_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=45,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Brown}},
	Center_45_LightYellow_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=45,
					richText=true,
					font = "font/art",
					normal={textColor=Color.LightYellow}},
	Left_30_Yellow2_Art = {alignment=TextAnchor.UpperLeft,
					fontSize=30,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Yellow2}},
	Center_45_Redbean_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=45,
					richText=true,
					font = "font/art",
					normal={textColor=Color.Redbean}},
	Left_45_ChannelColor_Art = {alignment=TextAnchor.UpperCenter,
					fontSize=45,
					richText=true,
					font = "font/art",
					normal={textColor=Color.ChannelColor1}},
}

GUIStyleTextField = {
	Left_20_White = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					padding={top=18,left=25},
					normal={background="Texture/Gui/Button/text_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_1",textColor=Color.White},},
	Left_20_White_Short = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					padding={top=14,left=25},
					normal={background="Texture/Gui/Button/text_3",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_3",textColor=Color.White},},
	Left_30_White = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					padding={top=18,left=25},
					normal={background="Texture/Gui/Button/text_1",textColor=Color.White}, 
					active={background="Texture/Gui/Button/text_1",textColor=Color.White},},
	Transparent = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					wordWrap=true,
					normal={textColor=Color.White},
					padding={top=14,left=25},},
	Transparent_25 = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					richText=true,
					clipping=TextClipping.Clip,
					normal={textColor=Color.White},
					padding={top=10,left=20},},
	MLeft_Transparent_30 = {alignment=TextAnchor.MiddleLeft,
					fontSize=20,
					richText=true,
					clipping=TextClipping.Clip,
					normal={textColor=Color.White},
					padding={top=10,left=20},},
	Left_30_White_2 = {alignment=TextAnchor.UpperLeft,
					fontSize=20,
					-- richText=true,
					-- wordWrap=true,
					padding={top=13,left=15},
					normal={background="Texture/Gui/Bg/bg49_1",textColor=Color.White}, 
					active={background="Texture/Gui/Bg/bg49_1",textColor=Color.White},},
}

